#!/usr/bin/env python3
"""Decode the "RTL_TOKENS: …" line from a tb_autoregress_bfp run via
the SmolLM2 tokenizer.  Renders the on-chip BFP autoregress output as
English text for human inspection.

Usage:  python3 decode_rtl_tokens.py <run.log>
"""
import sys, re
from transformers import AutoTokenizer

if len(sys.argv) != 2:
    sys.exit(f"usage: {sys.argv[0]} <run.log>")
log = open(sys.argv[1]).read()
m = re.search(r'^RTL_TOKENS:\s*(.+)$', log, re.MULTILINE)
if not m:
    sys.exit("no RTL_TOKENS: line found in log")
ids = [int(x) for x in m.group(1).split()]
tok = AutoTokenizer.from_pretrained('HuggingFaceTB/SmolLM2-135M')
print(f"# {len(ids)} tokens generated by on-chip BFP autoregress")
print(repr(tok.decode(ids)))
print()
print("Rendered:")
print(tok.decode(ids))
