#!/usr/bin/env python3
"""Single source of truth for the engine regmap (jtag_word_addr, 10-bit).

Edit the NAMED table below and run `make regmap` (it is also a build prereq of
the firmware and the bitstream).  Emits, from ONE table:

  ../generated/regmap_gen.svh   localparams for the SystemVerilog regmap
  src/soc/regmap_gen.h          a C enum for the PicoSoC firmware

so the RTL (vc707_microgpt_eth.sv) and the firmware (fw_engine.c) can never
disagree on an address.  The RESERVED set lists every other address the engine
regmap already uses, so adding a NAMED register that collides with ANYTHING is a
hard error — that is what keeps the bus non-overlapping.  Never write a bare
`10'hNNN` / `0xNNN` for these regs on either side; reference the symbol.

Why a generator and not a hand-shared header: SV and C preprocessors differ
(`localparam`/backtick vs `#define`), so a single literal header can't serve
both; generating both from one Python table is the robust way (mirrors
host/gen_build_version.py).
"""
import os
import sys

# (NAME, addr, access, description).  access: R / W / RW (documentation only).
NAMED = [
    ("R_MAGIC",      0x000, "R",  "'MGRT' magic / probe"),
    ("R_DBG_CALIB",  0x012, "R",  "[0] init_calib_complete + dbg snap bits"),
    ("R_ML_STATE",   0x017, "R",  "[2:0] ml_state, [7:3] layer_idx, [8] lay_done"),
    ("R_ARM",        0x048, "W",  "any write: reset per-run snapshot + weight CRC"),
    ("R_HAS_RUN",    0x049, "R",  "[0] autoregress completed since restart"),
    ("R_CRC",        0x04A, "R",  "engine RUN weight hash (unpacked weight bus)"),
    ("R_AXI_AR_CNT", 0x050, "R",  "BFP AXI AR-accept count (diag)"),
    ("R_AXI_R_CNT",  0x051, "R",  "BFP AXI R-beat count (diag)"),
    ("R_AXI_ARADDR", 0x052, "R",  "last accepted araddr (diag)"),
    # ---- idle DDR3 scan-CRC (verify an upload without running inference) ----
    ("R_SCAN_BASE",  0x080, "W",  "idle scan base byte addr (64B aligned)"),
    ("R_SCAN_LEN",   0x081, "W",  "idle scan length in 512-bit beats"),
    ("R_SCAN_TRIG",  0x082, "W",  "[0] write 1 -> start idle scan-CRC"),
    ("R_SCAN_STAT",  0x083, "R",  "[0] busy, [1] done"),
    ("R_SCAN_CRC",   0x084, "R",  "idle scan-CRC result (raw 512b-beat hash)"),
    # ---- matvec selftest (stubbed unless MICROGPT_NO_OP_TESTS is off) ----
    ("R_MVST_R0",    0x100, "R",  "matvec selftest result base (8 words 0x100..0x107)"),
    ("R_MVST_DONE",  0x108, "R",  "[0] matvec selftest done"),
    ("R_MVST_TRIG",  0x109, "W",  "[0] write 1 -> retrigger matvec selftest"),
    ("R_BUILDVER",   0x10F, "R",  "BUILD_VERSION (git HEAD short hash)"),
    ("R_LAYER_DONE", 0x1F0, "R",  "[0] lay_done, [1] lay_done_latched"),
    ("R_RESTART",    0x1F1, "W",  "[0] write 1 -> restart pulse (clears CRC/has_run)"),
]

# Every OTHER engine-regmap address currently in use (vc707_microgpt_eth.sv).
# Not emitted as symbols — listed only so a new NAMED address that lands on one
# is rejected.  Keep in sync if you repurpose any of these.
RESERVED = [
    0x001, 0x002, 0x003, 0x004, 0x005, 0x006, 0x007, 0x008, 0x009, 0x00A,
    0x00B, 0x00C, 0x00D, 0x00E, 0x00F, 0x010, 0x011, 0x013, 0x014, 0x018,
    0x019, 0x01A, 0x01B, 0x01C, 0x01D, 0x024, 0x028, 0x034, 0x036, 0x037,
    0x040, 0x044, 0x060, 0x061, 0x062, 0x063, 0x064, 0x065, 0x066, 0x067,
    0x068, 0x06A, 0x070, 0x071, 0x072, 0x101, 0x102, 0x103, 0x104, 0x105,
    0x106, 0x107, 0x110, 0x11E, 0x130, 0x131, 0x140, 0x15E, 0x160, 0x161,
    0x170, 0x180, 0x190, 0x191, 0x19E, 0x1A0, 0x1C0, 0x1C1, 0x1D0, 0x200,
    0x320,
]

HERE = os.path.dirname(os.path.abspath(__file__))
SVH  = os.path.abspath(os.path.join(HERE, "..", "..", "generated", "regmap_gen.svh"))
H    = os.path.abspath(os.path.join(HERE, "..", "src", "soc", "regmap_gen.h"))


def validate():
    seen = {}
    for name, addr, _acc, _d in NAMED:
        if addr > 0x3FF:
            sys.exit(f"ERROR: {name}=0x{addr:03X} exceeds the 10-bit regmap space")
        if addr in seen:
            sys.exit(f"ERROR: address 0x{addr:03X} reused: {seen[addr]} and {name}")
        seen[addr] = name
    for addr in RESERVED:
        if addr in seen:
            sys.exit(f"ERROR: NAMED {seen[addr]} collides with RESERVED 0x{addr:03X}")
        seen[addr] = "<reserved>"


def emit_svh():
    w = max(len(n) for n, *_ in NAMED)
    lines = [
        "// AUTO-GENERATED by host/gen_regmap.py — do not edit.",
        "// Single source of truth for the engine regmap; see also src/soc/regmap_gen.h.",
        "",
    ]
    for name, addr, acc, desc in NAMED:
        lines.append(f"localparam logic [9:0] {name:<{w}} = 10'h{addr:03X};  // {acc:<2} {desc}")
    lines.append("")
    os.makedirs(os.path.dirname(SVH), exist_ok=True)
    with open(SVH, "w") as f:
        f.write("\n".join(lines))


def emit_h():
    w = max(len(n) for n, *_ in NAMED)
    lines = [
        "/* AUTO-GENERATED by host/gen_regmap.py — do not edit. */",
        "/* Single source of truth for the engine regmap; see also regmap_gen.svh. */",
        "#ifndef REGMAP_GEN_H",
        "#define REGMAP_GEN_H",
        "",
        "enum engine_regmap {",
    ]
    for name, addr, acc, desc in NAMED:
        lines.append(f"    {name:<{w}} = 0x{addr:03X},  /* {acc:<2} {desc} */")
    lines += ["};", "", "#endif /* REGMAP_GEN_H */", ""]
    os.makedirs(os.path.dirname(H), exist_ok=True)
    with open(H, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    validate()
    emit_svh()
    emit_h()
    print(f"gen_regmap: {len(NAMED)} named regs, {len(RESERVED)} reserved -> "
          f"{os.path.relpath(SVH)} + {os.path.relpath(H)}")
