#!/usr/bin/env python3
"""Emit a SystemVerilog include with a 32-bit build version constant.

Bakes the current Unix epoch (low 32 bits) into the bitstream so the host
can read a register to confirm which firmware is actually running.  Also
embeds a short ASCII tag for log inspection.

Output: ../generated/build_version.svh

  localparam logic [31:0] BUILD_VERSION = 32'h<epoch_low32>;
  // Build time:  YYYY-MM-DD HH:MM:SS
"""
import os
import sys
import time

OUT = os.path.join(os.path.dirname(__file__), "..", "generated", "build_version.svh")
OUT = os.path.abspath(OUT)

def main():
    epoch = int(time.time())
    low32 = epoch & 0xFFFFFFFF
    stamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(epoch))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by host/gen_build_version.py — do not edit.\n")
        f.write(f"// Build time: {stamp}  (epoch {epoch})\n\n")
        f.write(f"localparam logic [31:0] BUILD_VERSION = 32'h{low32:08x};\n")
    print(f"wrote {OUT}  (BUILD_VERSION = 0x{low32:08x}  / {stamp})", file=sys.stderr)

if __name__ == "__main__":
    main()
