#!/usr/bin/env python3
"""Generate FPGA rmsnorm self-test data + Python reference.

Emits a SystemVerilog include file with packed localparam constants for the
two input ROMs (x and gamma).  We avoid `$readmemh` because Vivado has
intermittently rejected it for memories that are read combinationally
(see project memory: matvec_selftest scale_rom).  A flat localparam is
unambiguous: no memory inference required, no synth quirks.

Outputs (in ../generated/):
  rmsnorm_selftest_data.svh       two `localparam logic [D*16-1:0]` packed
                                  into a single SV literal each.  Lane 0 in
                                  bits [15:0].
  rmsnorm_selftest_expected.txt   D lines of "<hex16>  <signed_decimal>"
                                  reference output (numpy-computed,
                                  bit-exact-comparable to the engine).
"""
import os
import sys
import numpy as np

D       = 64
EPS_R   = 1e-5
OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "generated"))


def saturate_q15(v):
    return np.clip(v, -32768, 32767).astype(np.int16)


def pack_lane0_low(values: np.ndarray) -> str:
    """Pack 16-bit values into a single hex string with lane 0 in the low
    bits — i.e. value at index 0 is rightmost in the resulting hex literal."""
    return "".join(f"{int(v) & 0xFFFF:04x}" for v in reversed(values))


def main():
    rng = np.random.default_rng(0xBEEF)

    x_real     = rng.normal(0, 0.25, size=D).astype(np.float64)
    gamma_real = rng.normal(0, 0.5,  size=D).astype(np.float64)
    x_q15     = saturate_q15(np.round(x_real     * (1 << 15)))
    gamma_q15 = saturate_q15(np.round(gamma_real * (1 << 15)))

    # Reference using the *quantized* x and gamma
    x_dq    = x_q15.astype(np.float64)     / (1 << 15)
    g_dq    = gamma_q15.astype(np.float64) / (1 << 15)
    mean_sq = np.mean(x_dq * x_dq)
    inv_rms = 1.0 / np.sqrt(mean_sq + EPS_R)
    y_real  = x_dq * g_dq * inv_rms
    y_q15   = saturate_q15(np.round(y_real * (1 << 15)))

    os.makedirs(OUT_DIR, exist_ok=True)

    x_hex = pack_lane0_low(x_q15)
    g_hex = pack_lane0_low(gamma_q15)
    bits  = D * 16

    with open(os.path.join(OUT_DIR, "rmsnorm_selftest_data.svh"), "w") as f:
        f.write("// AUTO-GENERATED by host/gen_rmsnorm_selftest.py — do not edit.\n")
        f.write(f"// {D} × Q1.15 input vectors, lane 0 at bits [15:0] of each literal.\n\n")
        f.write(f"localparam logic [{bits-1}:0] RMSNORM_X_PACKED     = {bits}'h{x_hex};\n")
        f.write(f"localparam logic [{bits-1}:0] RMSNORM_GAMMA_PACKED = {bits}'h{g_hex};\n")

    with open(os.path.join(OUT_DIR, "rmsnorm_selftest_expected.txt"), "w") as f:
        f.write("# rmsnorm_selftest expected output (int16 Q1.15)\n")
        for v in y_q15:
            f.write(f"{int(v) & 0xFFFF:04x}  {int(v):+7d}\n")

    n_sat = int(np.sum((y_q15 == 32767) | (y_q15 == -32768)))
    print(f"D={D}  inv_rms={inv_rms:.4f}  saturated lanes: {n_sat}/{D}", file=sys.stderr)
    print(f"wrote {OUT_DIR}/rmsnorm_selftest_data.svh + expected.txt", file=sys.stderr)


if __name__ == "__main__":
    main()
