#!/usr/bin/env python3
"""Generate FPGA rope self-test data + Python reference.

Emits a SystemVerilog include file with a packed localparam for the input
vector and a scalar localparam for the position index.  Avoids $readmemh
for the test-input ROM — uses packed localparam literals instead.

Outputs (in ../generated/):
  rope_selftest_data.svh        two localparams: ROPE_X_PACKED + ROPE_POS
  rope_selftest_expected.txt    HEAD_DIM lines of "<hex16>  <signed_decimal>"
                                reference output (LLaMA-style rotation, same
                                math as gen_rope_test.py).
"""
import os
import sys
import numpy as np

HEAD_DIM = 64
MAX_CTX  = 2048
BASE     = 10000.0
POS      = 137   # arbitrary non-trivial position

OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "generated"))


def saturate_q15(v):
    return np.clip(v, -32768, 32767).astype(np.int16)


def pack_lane0_low(values: np.ndarray) -> str:
    """Pack 16-bit values into a single hex string, lane 0 in the low bits."""
    return "".join(f"{int(v) & 0xFFFF:04x}" for v in reversed(values))


def main():
    rng = np.random.default_rng(0xDADA)

    x_real = rng.normal(0, 0.4, size=HEAD_DIM).astype(np.float64)
    x_q15  = saturate_q15(np.round(x_real * (1 << 15)))

    # Re-dequantize for reference so we only test the engine, not quant rounding
    x_dq = x_q15.astype(np.float64) / (1 << 15)

    H2    = HEAD_DIM // 2
    j     = np.arange(H2)
    freq  = 1.0 / (BASE ** (2.0 * j / HEAD_DIM))
    angle = POS * freq

    # Quantise cos/sin the same way the LUT generator does — use the LUT
    # values (Q1.15) for the reference, not floating-point cos/sin directly.
    cos_q15 = saturate_q15(np.round(np.cos(angle) * (1 << 15)))
    sin_q15 = saturate_q15(np.round(np.sin(angle) * (1 << 15)))

    c_dq = cos_q15.astype(np.float64) / (1 << 15)
    s_dq = sin_q15.astype(np.float64) / (1 << 15)

    x_lo = x_dq[:H2]
    x_hi = x_dq[H2:]

    y_lo =  x_lo * c_dq - x_hi * s_dq
    y_hi =  x_hi * c_dq + x_lo * s_dq
    y_real = np.concatenate([y_lo, y_hi])
    y_q15  = saturate_q15(np.round(y_real * (1 << 15)))

    os.makedirs(OUT_DIR, exist_ok=True)

    x_hex = pack_lane0_low(x_q15)
    bits  = HEAD_DIM * 16

    pos_bits = (MAX_CTX - 1).bit_length()   # 11 for MAX_CTX=2048

    with open(os.path.join(OUT_DIR, "rope_selftest_data.svh"), "w") as f:
        f.write("// AUTO-GENERATED by host/gen_rope_selftest.py — do not edit.\n")
        f.write(f"// {HEAD_DIM} x Q1.15 input vector, lane 0 at bits [15:0].\n\n")
        f.write(f"localparam logic [{bits-1}:0] ROPE_X_PACKED = {bits}'h{x_hex};\n")
        f.write(f"localparam logic [{pos_bits-1}:0] ROPE_POS = {pos_bits}'d{POS};\n")

    with open(os.path.join(OUT_DIR, "rope_selftest_expected.txt"), "w") as f:
        f.write("# rope_selftest expected output (int16 Q1.15)\n")
        for v in y_q15:
            f.write(f"{int(v) & 0xFFFF:04x}  {int(v):+7d}\n")

    n_sat = int(np.sum((y_q15 == 32767) | (y_q15 == -32768)))
    print(f"HEAD_DIM={HEAD_DIM}  pos={POS}  saturated lanes: {n_sat}/{HEAD_DIM}",
          file=sys.stderr)
    print(f"wrote {OUT_DIR}/rope_selftest_data.svh + expected.txt", file=sys.stderr)


if __name__ == "__main__":
    main()
