#!/usr/bin/env python3
"""Emit a SystemVerilog include with a 32-bit build version constant.

BUILD_VERSION = the git HEAD short hash (first 8 hex of the SHA), so the
host can read register 0x10F and map the running bitstream to an exact
commit.  A date stamp couldn't distinguish builds and was prone to being
shadowed by a stale committed copy.  Refuses to emit a hash for a dirty
Verilog tree (override with ALLOW_DIRTY=1) so the hash stays meaningful.

NOTE: scripts/run.tcl generates this inline during synth — this script is
a standalone equivalent for manual use; keep the two in sync.

Output: ../generated/build_version.svh

  localparam logic [31:0] BUILD_VERSION = 32'h<git_short_hash>;
"""
import os
import subprocess
import sys

# rtl/generated (= run.tcl's ../generated), NOT rtl/vc707/generated which is
# not on Vivado's include path.  host/ is rtl/vc707/host, so go up two.
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "generated", "build_version.svh")
OUT = os.path.abspath(OUT)

def _build_shaping(path):
    """True if an uncommitted file would change the synthesized bitstream and
    so make the git-hash BUILD_VERSION misleading.  Covers Verilog, synthesis
    constraints/scripts, the Makefile, and the gen_*.py bakers — but NOT host
    tools (cosim drivers) or runtime artifacts (PROMPT.hex, release/), and
    never anything under generated/."""
    if not path or "generated/" in path:
        return False
    base = os.path.basename(path)
    if path.endswith((".sv", ".svh", ".v", ".vh", ".xdc")):
        return True
    if path.endswith(".tcl") and "scripts/" in path:
        return True
    if base == "Makefile":
        return True
    if base.startswith("gen_") and base.endswith(".py"):
        return True
    return False


def main():
    sha = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode().strip()
    git8 = sha[:8]
    porc = subprocess.check_output(["git", "status", "--porcelain"]).decode().splitlines()
    dirty = []
    for ln in porc:
        f = ln[3:].strip()
        if " -> " in f:            # rename: take the new path
            f = f.split(" -> ")[-1]
        if _build_shaping(f):
            dirty.append(f)
    if dirty and not os.environ.get("ALLOW_DIRTY"):
        sys.stderr.write("ERROR: uncommitted build-shaping sources (Verilog / synth "
                         f"scripts / Makefile / gen_*.py) — commit so BUILD_VERSION\n"
                         f"       (git 0x{git8}) maps to a commit, or set ALLOW_DIRTY=1:\n")
        for f in dirty:
            sys.stderr.write(f"         {f}\n")
        sys.exit(1)
    dsuf = " DIRTY" if dirty else ""
    # Deterministic content (NO volatile timestamp) so the file is rewritten
    # only when the hash / dirty-state changes — keeps make from forcing a
    # needless full re-synth on every invocation.
    body = ("// AUTO-GENERATED by host/gen_build_version.py — do not edit.\n"
            f"// git HEAD: {sha}{dsuf}\n\n"
            f"localparam logic [31:0] BUILD_VERSION = 32'h{git8};\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    if os.path.exists(OUT) and open(OUT).read() == body:
        print(f"build_version.svh up-to-date (BUILD_VERSION = 0x{git8}{dsuf})", file=sys.stderr)
        return
    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {OUT}  (BUILD_VERSION = 0x{git8}{dsuf})", file=sys.stderr)

if __name__ == "__main__":
    main()
