#!/usr/bin/env python3
"""Generate FPGA swiglu self-test data + Python reference.

Emits a SystemVerilog include file with packed localparam constants for the
gate and up input ROMs.  We avoid `$readmemh` because Vivado has intermittently
rejected it for memories that are read combinationally.  A flat localparam is
unambiguous: no memory inference required, no synth quirks.

Outputs (in ../generated/):
  swiglu_selftest_data.svh        two `localparam logic [N*16-1:0]` packed
                                  into a single SV literal each.  Lane 0 in
                                  bits [15:0].
  swiglu_selftest_expected.txt    N lines of "<hex16>  <signed_decimal>"
                                  reference output (numpy-computed,
                                  bit-exact-comparable to the engine).
"""
import os
import sys
import numpy as np

N       = 64
OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "generated"))


def saturate_q15(v):
    return np.clip(v, -32768, 32767).astype(np.int16)


def pack_lane0_low(values: np.ndarray) -> str:
    """Pack 16-bit values into a single hex string with lane 0 in the low
    bits — i.e. value at index 0 is rightmost in the resulting hex literal."""
    return "".join(f"{int(v) & 0xFFFF:04x}" for v in reversed(values))


def silu_q15(x_q15: np.ndarray) -> np.ndarray:
    """Compute SiLU(x) in Q1.15 matching the LUT-based hardware exactly.

    The hardware indexes the 65536-entry LUT by the full 16-bit two's-complement
    value, so we replicate that: convert to float, compute silu, re-quantise.
    """
    x_f = x_q15.astype(np.float64) / 32768.0
    silu_f = x_f / (1.0 + np.exp(-x_f))
    return saturate_q15(np.round(silu_f * 32768.0))


def main():
    rng = np.random.default_rng(0xCAFE)

    gate_real = rng.normal(0, 0.5, size=N).astype(np.float64)
    up_real   = rng.normal(0, 0.5, size=N).astype(np.float64)

    gate_q15 = saturate_q15(np.round(gate_real * 32768.0))
    up_q15   = saturate_q15(np.round(up_real   * 32768.0))

    # Reference: silu(gate) * up, matching hardware arithmetic
    silu_gate = silu_q15(gate_q15)                        # Q1.15
    product   = silu_gate.astype(np.int32) * up_q15.astype(np.int32)  # Q2.30
    shifted   = product >> 15                             # arithmetic shift
    y_q15     = saturate_q15(shifted)

    os.makedirs(OUT_DIR, exist_ok=True)

    gate_hex = pack_lane0_low(gate_q15)
    up_hex   = pack_lane0_low(up_q15)
    bits     = N * 16

    with open(os.path.join(OUT_DIR, "swiglu_selftest_data.svh"), "w") as f:
        f.write("// AUTO-GENERATED by host/gen_swiglu_selftest.py — do not edit.\n")
        f.write(f"// {N} × Q1.15 input vectors, lane 0 at bits [15:0] of each literal.\n\n")
        f.write(f"localparam logic [{bits-1}:0] SWIGLU_GATE_PACKED = {bits}'h{gate_hex};\n")
        f.write(f"localparam logic [{bits-1}:0] SWIGLU_UP_PACKED   = {bits}'h{up_hex};\n")

    with open(os.path.join(OUT_DIR, "swiglu_selftest_expected.txt"), "w") as f:
        f.write("# swiglu_selftest expected output (int16 Q1.15)\n")
        for v in y_q15:
            f.write(f"{int(v) & 0xFFFF:04x}  {int(v):+7d}\n")

    n_sat = int(np.sum((y_q15 == 32767) | (y_q15 == -32768)))
    print(f"N={N}  saturated lanes: {n_sat}/{N}", file=sys.stderr)
    print(f"wrote {OUT_DIR}/swiglu_selftest_data.svh + expected.txt", file=sys.stderr)


if __name__ == "__main__":
    main()
