#!/usr/bin/env python3
"""Generate FPGA matvec self-test data + Python reference.

Writes three hex files to ../generated/ for $readmemh in matvec_selftest.sv:

  matvec_selftest_act.hex      IN_DIM lines of 4 hex digits   (int16 activation)
  matvec_selftest_weights.hex  IN_DIM lines of 32 hex digits  (16 lanes × 8-bit weights, lane 0 in low byte)
  matvec_selftest_scale.hex    16 lines of 4 hex digits       (int16 Q1.15 scale)

Also writes matvec_selftest_expected.txt with the 16 expected output values
(int16 Q1.15) for the host verifier to compare against.

The data matches what the Verilator matvec testbench (gen_matvec_test.py)
exercises — same algorithmic mimic, just laid out for FPGA $readmemh.
"""
import numpy as np
import os
import sys

LANES  = 16
IN_DIM = 64
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "generated")
OUT_DIR = os.path.abspath(OUT_DIR)


def main():
    rng = np.random.default_rng(0xF00D)

    # int16 activations (Q1.15).  Keep magnitudes ≤ 32k (full range).
    act = rng.integers(-32768, 32767, size=IN_DIM, dtype=np.int16)

    # int8 weights laid out as [k][lane] so lane 0 is in the low byte of the
    # packed 128-bit weight word (matching matvec_int8_engine's w_int8 bus).
    w = rng.integers(-127, 127, size=(LANES, IN_DIM), dtype=np.int8)

    # Q1.15 per-lane scale.  Keep |scale| ≤ 8192 so post-shift outputs don't
    # all just saturate.
    scale = rng.integers(-8192, 8192, size=LANES, dtype=np.int16)

    # Reference: bit-exact integer mimic of matvec_int8_engine.
    acc = np.zeros(LANES, dtype=np.int64)
    for k in range(IN_DIM):
        acc += act[k].astype(np.int64) * w[:, k].astype(np.int64)
    out = np.zeros(LANES, dtype=np.int16)
    for l in range(LANES):
        s = int(acc[l]) * int(scale[l])
        sh = s >> 15
        out[l] = max(-32768, min(32767, sh))

    os.makedirs(OUT_DIR, exist_ok=True)

    # Activation: one int16 per line, 4 hex digits.
    with open(os.path.join(OUT_DIR, "matvec_selftest_act.hex"), "w") as f:
        for v in act:
            f.write(f"{int(v) & 0xFFFF:04x}\n")

    # Weights: one 128-bit packed line per k.  Lane 0 in low byte.
    with open(os.path.join(OUT_DIR, "matvec_selftest_weights.hex"), "w") as f:
        for k in range(IN_DIM):
            packed = 0
            for l in range(LANES):
                packed |= (int(w[l, k]) & 0xFF) << (l * 8)
            f.write(f"{packed:032x}\n")

    # Scale: one int16 per line.  Lane 0 first (matches scale_q15 bus where
    # scale_q15[15:0] is lane 0).
    with open(os.path.join(OUT_DIR, "matvec_selftest_scale.hex"), "w") as f:
        for v in scale:
            f.write(f"{int(v) & 0xFFFF:04x}\n")

    with open(os.path.join(OUT_DIR, "matvec_selftest_expected.txt"), "w") as f:
        f.write(f"# matvec_selftest expected output (int16 Q1.15, lane 0 first)\n")
        for v in out:
            f.write(f"{int(v) & 0xFFFF:04x}  {int(v):+7d}\n")

    # SystemVerilog include: scale ROM as a single 256-bit localparam.
    # Originally this was a function with a case statement, but Vivado
    # synthesis appeared to mishandle the loop-driven function call,
    # producing tiny output values (~±128).  A direct localparam constant
    # is unambiguous: no $readmemh issues, no function-call ambiguity.
    # Lane 0 occupies bits [15:0]; the literal is therefore a concatenation
    # with lane 15 at the MSB end.
    packed_hex = "".join(f"{int(scale[l]) & 0xFFFF:04x}" for l in reversed(range(LANES)))
    # group as 4 underscores for readability: 4 hex digits per lane
    packed_pretty = "_".join(packed_hex[i:i+4] for i in range(0, len(packed_hex), 4))
    with open(os.path.join(OUT_DIR, "matvec_selftest_scale.svh"), "w") as f:
        f.write("// AUTO-GENERATED by host/gen_matvec_selftest.py — do not edit.\n")
        f.write("// 16-lane Q1.15 scale ROM, packed lane 0 in [15:0] .. lane 15 in [255:240].\n\n")
        f.write(f"localparam logic [255:0] SCALE_PACKED_INIT = 256'h{packed_pretty};\n")

    print(f"wrote {OUT_DIR}/matvec_selftest_*.hex + .svh", file=sys.stderr)
    print(f"expected = {out.tolist()}", file=sys.stderr)


if __name__ == "__main__":
    main()
