#!/usr/bin/env python3
"""
gen_layer_ddr3.py — pack the 7 per-matrix layer_W_*.hex files into one
DDR3 memory image and emit the per-matrix base addresses as a Verilog
header.

Used by:
  - sim/tb_smollm_layer_ddr3 (mock_axi_slave loads the packed image)
  - the FPGA host (uploads the packed image to DDR3)

Inputs  (must already exist in <repo>/rtl/vc707/generated/):
  layer_W_Q.hex layer_W_K.hex layer_W_V.hex layer_W_O.hex
  layer_W_GATE.hex layer_W_UP.hex layer_W_DOWN.hex

Outputs (written to <repo>/rtl/vc707/generated/):
  layer_DDR3.hex            — one 128-bit hex entry per line, padded with
                              zeros between matrices for tile alignment.
  layer_ddr3_bases.svh      — `define MICROGPT_LAYER_BASE_Q 30'h..., etc.

Layout: each matrix starts at a TILE-aligned (8 KiB) offset.  Matrices
are placed in order Q, K, V, O, GATE, UP, DOWN.  Total image size is
typically ~3.5 MB for SmolLM2 real dims (D=576, FFN=1536).
"""

import argparse
import os
import math

HERE      = os.path.dirname(__file__)
GENDIR    = os.path.normpath(os.path.join(HERE, "..", "generated"))

MATRICES  = ["Q", "K", "V", "O", "GATE", "UP", "DOWN"]
TILE_BYTES = 8192        # 8 KiB AXI burst

def read_hex(path):
    """Returns list of 128-bit ints (one per line)."""
    with open(path) as f:
        return [int(line.strip(), 16) for line in f if line.strip()]

def align_up(x, a):
    return ((x + a - 1) // a) * a

def build_layer_image(prefix):
    """Read W_<m>.hex files matching <prefix>W_<m>.hex; return (matrices, bases, layer_bytes)."""
    matrices = {}
    for m in MATRICES:
        path = os.path.join(GENDIR, f"{prefix}W_{m}.hex")
        matrices[m] = read_hex(path)
    bases = {}
    cursor_bytes = 0
    for m in MATRICES:
        bases[m] = cursor_bytes
        cursor_bytes += len(matrices[m]) * 16
        cursor_bytes = align_up(cursor_bytes, TILE_BYTES)
    return matrices, bases, cursor_bytes


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["single", "tm"], default="single",
                    help="single = one layer (default; reads layer_W_*.hex). "
                         "tm = NL layers concatenated at LAYER_BYTES intervals "
                         "(reads tm_layer_L<N>_W_*.hex).")
    ap.add_argument("--nlayers", type=int, default=3,
                    help="Layer count when --mode tm")
    ap.add_argument("--layer-align", type=int, default=64*1024,
                    help="Align each layer's image to this byte boundary "
                         "in the multi-layer image (default 64 KiB)")
    args = ap.parse_args()

    if args.mode == "tm":
        return main_tm(args)

    matrices, bases, cursor_bytes = build_layer_image("layer_")
    for m in MATRICES:
        print(f"  W_{m:<4}: {len(matrices[m]):>6} × 128-bit entries "
              f"= {len(matrices[m]) * 16:>8} B")
    total_entries = cursor_bytes // 16
    total_bytes   = cursor_bytes

    print()
    print(f"  Total: {total_bytes:>8} B = {total_bytes/1024:.1f} KiB"
          f" = {total_entries} × 128-bit entries")
    print()

    # Build the packed image (zero-padded).
    image = [0] * total_entries
    for m in MATRICES:
        off_entries = bases[m] // 16
        for i, w in enumerate(matrices[m]):
            image[off_entries + i] = w

    # Emit packed image hex (for $readmemh / mock_axi_slave)
    out_hex = os.path.join(GENDIR, "layer_DDR3.hex")
    with open(out_hex, "w") as f:
        for w in image:
            f.write(f"{w:032x}\n")
    print(f"  wrote {out_hex}")

    # Emit packed image binary (for `ddr_write.py layer_DDR3.bin`).
    # Each 128-bit entry is little-endian 16 bytes; the FPGA AXI slave
    # returns it as 4 contiguous 16-byte slabs per 64-byte beat.
    out_bin = os.path.join(GENDIR, "layer_DDR3.bin")
    with open(out_bin, "wb") as f:
        for w in image:
            f.write(w.to_bytes(16, byteorder="little"))
    print(f"  wrote {out_bin}")

    # Emit bases header
    out_svh = os.path.join(GENDIR, "layer_ddr3_bases.svh")
    with open(out_svh, "w") as f:
        f.write("// Auto-generated by gen_layer_ddr3.py — do not edit.\n")
        f.write("// Per-matrix DDR3 byte offsets for the layer-test image.\n")
        f.write("// Pass these to smollm_layer's BASE_* parameters.\n\n")
        for m in MATRICES:
            f.write(f"`define MICROGPT_LAYER_BASE_{m}  30'h{bases[m]:08x}\n")
        f.write(f"`define MICROGPT_LAYER_DDR3_ENTRIES {total_entries}\n")
    print(f"  wrote {out_svh}")
    for m in MATRICES:
        print(f"    BASE_{m:<4} = 0x{bases[m]:08x}")

def main_tm(args):
    """Multi-layer TM image: NL per-layer images concatenated at
    LAYER_BYTES intervals (= layer_align rounded up from one layer's size).
    Per-matrix offsets WITHIN a layer are identical to single-mode."""
    NL = args.nlayers
    print(f"  TM mode: NL={NL} layers, reading tm_layer_L<n>_W_*.hex")

    # Build first layer image to discover the per-matrix bases + per-layer size.
    mats0, bases, layer_size_natural = build_layer_image("tm_layer_L0_")
    layer_bytes = align_up(layer_size_natural, args.layer_align)
    print(f"  per-layer size: {layer_size_natural:>8} B → padded to {layer_bytes} B "
          f"(align={args.layer_align})")
    for m in MATRICES:
        print(f"    BASE_{m:<4} (within layer) = 0x{bases[m]:08x}, "
              f"{len(mats0[m]):>6} × 128b entries")

    total_bytes = layer_bytes * NL
    total_entries = total_bytes // 16
    print(f"  TOTAL image: {total_bytes:>10} B = {total_bytes/1024/1024:.1f} MiB "
          f"= {total_entries} × 128-bit entries")

    # Build the concatenated image.
    image = [0] * total_entries
    for li in range(NL):
        prefix = f"tm_layer_L{li}_"
        mats_li, _, _ = build_layer_image(prefix)
        layer_off_entries = (li * layer_bytes) // 16
        for m in MATRICES:
            off = layer_off_entries + (bases[m] // 16)
            for i, w in enumerate(mats_li[m]):
                image[off + i] = w

    out_hex = os.path.join(GENDIR, "tm_layer_DDR3.hex")
    with open(out_hex, "w") as f:
        for w in image:
            f.write(f"{w:032x}\n")
    print(f"  wrote {out_hex}")

    out_bin = os.path.join(GENDIR, "tm_layer_DDR3.bin")
    with open(out_bin, "wb") as f:
        for w in image:
            f.write(w.to_bytes(16, byteorder="little"))
    print(f"  wrote {out_bin}")

    out_svh = os.path.join(GENDIR, "tm_layer_ddr3_bases.svh")
    with open(out_svh, "w") as f:
        f.write("// Auto-generated by gen_layer_ddr3.py --mode tm — do not edit.\n")
        f.write("// Per-matrix offsets WITHIN ONE layer; layer N's matrix M is at\n")
        f.write("// (N * MICROGPT_TM_LAYER_BYTES) + MICROGPT_TM_BASE_M.\n\n")
        for m in MATRICES:
            f.write(f"`define MICROGPT_TM_BASE_{m}  30'h{bases[m]:08x}\n")
        f.write(f"`define MICROGPT_TM_LAYER_BYTES   30'h{layer_bytes:08x}\n")
        f.write(f"`define MICROGPT_TM_DDR3_ENTRIES  {total_entries}\n")
        f.write(f"`define MICROGPT_TM_NL            {NL}\n")
    print(f"  wrote {out_svh}")


if __name__ == "__main__":
    main()
