#!/usr/bin/env python3
"""Emit a SystemVerilog include with a 32-bit build version constant.

BUILD_VERSION = the git HEAD short hash (first 8 hex of the SHA), so the
host can read register 0x10F and map the running bitstream to an exact
commit.  A date stamp couldn't distinguish builds and was prone to being
shadowed by a stale committed copy.  Refuses to emit a hash for a dirty
Verilog tree (override with ALLOW_DIRTY=1) so the hash stays meaningful.

NOTE: scripts/run.tcl generates this inline during synth — this script is
a standalone equivalent for manual use; keep the two in sync.

Output: ../generated/build_version.svh

  localparam logic [31:0] BUILD_VERSION = 32'h<git_short_hash>;
"""
import os
import subprocess
import sys
import time

# rtl/generated (= run.tcl's ../generated), NOT rtl/vc707/generated which is
# not on Vivado's include path.  host/ is rtl/vc707/host, so go up two.
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "generated", "build_version.svh")
OUT = os.path.abspath(OUT)

def main():
    sha = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode().strip()
    git8 = sha[:8]
    porc = subprocess.check_output(["git", "status", "--porcelain"]).decode().splitlines()
    dirty = [ln[3:].strip() for ln in porc
             if ln[3:].strip().endswith((".sv", ".svh", ".v", ".vh"))
             and "generated/" not in ln]
    if dirty and not os.environ.get("ALLOW_DIRTY"):
        sys.stderr.write("ERROR: uncommitted Verilog — commit so BUILD_VERSION "
                         f"(git 0x{git8}) maps to a commit, or set ALLOW_DIRTY=1:\n")
        for f in dirty:
            sys.stderr.write(f"         {f}\n")
        sys.exit(1)
    dsuf = " DIRTY" if dirty else ""
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by host/gen_build_version.py — do not edit.\n")
        f.write(f"// git HEAD: {sha}{dsuf}\n")
        f.write(f"// built:    {stamp}\n\n")
        f.write(f"localparam logic [31:0] BUILD_VERSION = 32'h{git8};\n")
    print(f"wrote {OUT}  (BUILD_VERSION = 0x{git8}  git {git8}{dsuf})", file=sys.stderr)

if __name__ == "__main__":
    main()
