#!/usr/bin/env python3
"""Test data for `smollm_decode_head.sv` (Phase F.1).

The decode head is what runs after the last transformer layer:
    hidden_state (D-dim) → final-RMSNorm → lm_head matvec → argmax → token

Generates a random "post-layers hidden state" and checks the head's output
token matches the PyTorch-equivalent reference.

Outputs in ../generated/:
  decodehead_HIDDEN_IN.hex   D × Q1.15 (the post-layers hidden state)
  decodehead_GAMMA.hex       D × Q1.15 (final-norm gamma)
  decodehead_W_LM.hex        VOCAB/16 × D × 128-bit packed (lm_head INT8 weights)
  decodehead_SCALE_LM.hex    VOCAB × Q1.15 per-row scales
  decodehead_data.svh        VOCAB / D scalar constants
  decodehead_expected.txt    expected_token (a single decimal integer)
"""
import argparse
import os
import sys
import math
import numpy as np

from gen_layer_test import (
    quant_q15, dequant_q15, rmsnorm_pyref, matvec_int8_pyref,
    quant_int8_per_row,
)

OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "generated"))


def hex_byte(v): return f"{int(v) & 0xFF:02x}"
def hex_word(v): return f"{int(v) & 0xFFFF:04x}"


def write_hex(name, values, hexer):
    with open(os.path.join(OUT_DIR, name), "w") as f:
        for v in values:
            f.write(f"{hexer(v)}\n")


def write_packed_w(name, mat):
    out_dim, in_dim = mat.shape
    assert out_dim % 16 == 0
    n_chunks = out_dim // 16
    with open(os.path.join(OUT_DIR, name), "w") as f:
        for c in range(n_chunks):
            for k in range(in_dim):
                packed = 0
                for l in range(16):
                    packed |= (int(mat[c*16 + l, k]) & 0xFF) << (l * 8)
                f.write(f"{packed:032x}\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0xCAFE)
    args = ap.parse_args()

    D, VOCAB = 128, 128

    rng = np.random.default_rng(args.seed)
    w_std = 0.08 * math.sqrt(64.0 / D)

    # Random "post-layers hidden state" — typical magnitudes for a residual
    # stream after several transformer layers.  Stddev 0.3 keeps RMSNorm's
    # inv_rms in Q5.12 range.
    hidden = quant_q15(rng.normal(0, 0.3, D))
    gamma  = quant_q15(rng.normal(0, 0.3, D))

    # lm_head weights [VOCAB, D]
    W_lm_real     = rng.normal(0, w_std, (VOCAB, D))
    W_lm_int8, sca_lm = quant_int8_per_row(W_lm_real)

    # Reference forward
    normed = rmsnorm_pyref(hidden, gamma)
    logits = matvec_int8_pyref(W_lm_int8, sca_lm, normed)
    expected_token = int(np.argmax(logits))

    print(f"D={D}  VOCAB={VOCAB}  expected_token={expected_token}",
          file=sys.stderr)
    print(f"logits range [{logits.min()}, {logits.max()}]  "
          f"top-3 = {np.argsort(logits)[-3:][::-1].tolist()}", file=sys.stderr)

    os.makedirs(OUT_DIR, exist_ok=True)

    write_hex("decodehead_HIDDEN_IN.hex", hidden, hex_word)
    write_hex("decodehead_GAMMA.hex",     gamma,  hex_word)
    write_packed_w("decodehead_W_LM.hex", W_lm_int8)
    write_hex("decodehead_SCALE_LM.hex",  sca_lm, hex_word)

    with open(os.path.join(OUT_DIR, "decodehead_data.svh"), "w") as f:
        f.write("// AUTO-GENERATED by host/gen_decode_head_test.py — do not edit.\n")
        f.write(f"// D={D} VOCAB={VOCAB}\n\n")
        f.write(f"localparam int DH_D     = {D};\n")
        f.write(f"localparam int DH_VOCAB = {VOCAB};\n")

    with open(os.path.join(OUT_DIR, "decodehead_expected.txt"), "w") as f:
        f.write(f"# decode_head expected next-token (argmax over {VOCAB} logits)\n")
        f.write(f"{expected_token}\n")

    print(f"wrote decodehead_*.hex + .svh + .txt", file=sys.stderr)


if __name__ == "__main__":
    main()
