#!/usr/bin/env python3
"""Generate FPGA softmax_q15 self-test data + Python reference.

Emits a SystemVerilog include file with a packed localparam constant for the
input ROM (x).  A flat localparam is unambiguous: no memory inference required.

Outputs (in ../generated/):
  softmax_selftest_data.svh       one `localparam logic [N*16-1:0]` packed
                                  into a single SV literal.  Lane 0 in bits [15:0].
  softmax_selftest_expected.txt   N lines of "<hex16>  <signed_decimal>"
                                  reference output (numpy-computed,
                                  comparable to the engine within ±10 LSB).
"""
import os
import sys
import numpy as np

N       = 64
OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "generated"))


def saturate_q15_unsigned(v):
    return np.clip(v, 0, 32767).astype(np.int16)


def pack_lane0_low(values: np.ndarray) -> str:
    """Pack 16-bit values into a single hex string with lane 0 in the low
    bits — i.e. value at index 0 is rightmost in the resulting hex literal."""
    return "".join(f"{int(v) & 0xFFFF:04x}" for v in reversed(values))


def main():
    rng = np.random.default_rng(0xCAFE)

    # Inputs: typical post-1/sqrt(d_k) attention scores.
    x_real = rng.normal(0, 0.5, size=N).astype(np.float64)
    x_real = np.clip(x_real, -0.99, 0.99)
    x_q15  = np.clip(np.round(x_real * (1 << 15)), -32768, 32767).astype(np.int16)

    # Reference using the *quantized* x (so we measure only engine error).
    x_dq = x_q15.astype(np.float64) / (1 << 15)
    m    = x_dq.max()
    e    = np.exp(x_dq - m)
    y    = e / e.sum()
    y_q15 = saturate_q15_unsigned(np.round(y * (1 << 15)))

    os.makedirs(OUT_DIR, exist_ok=True)

    x_hex = pack_lane0_low(x_q15)
    bits  = N * 16

    with open(os.path.join(OUT_DIR, "softmax_selftest_data.svh"), "w") as f:
        f.write("// AUTO-GENERATED by host/gen_softmax_selftest.py — do not edit.\n")
        f.write(f"// {N} × Q1.15 input vector, lane 0 at bits [15:0] of the literal.\n\n")
        f.write(f"localparam logic [{bits-1}:0] SOFTMAX_X_PACKED = {bits}'h{x_hex};\n")

    with open(os.path.join(OUT_DIR, "softmax_selftest_expected.txt"), "w") as f:
        f.write("# softmax_selftest expected output (uint16 Q1.15, unsigned probability)\n")
        for v in y_q15:
            f.write(f"{int(v) & 0xFFFF:04x}  {int(v):+7d}\n")

    print(f"N={N}  y_q15 sum={y_q15.sum()}  (Q1.15 unit=32768)", file=sys.stderr)
    print(f"wrote {OUT_DIR}/softmax_selftest_data.svh + expected.txt", file=sys.stderr)


if __name__ == "__main__":
    main()
