#!/usr/bin/env python3
"""
gen_brom_sv.py — emit a SystemVerilog wrapper that instantiates one or
more RAMB36E1 primitives initialised with the contents of a Q15 .hex
file.  Replaces $readmemh-into-array+sync-read for the per-layer
gamma/scale ROMs in smollm_layer.sv: explicit primitives are
deterministic in Vivado (no LUTRAM fallback heuristic).

Layout: each RAMB36E1 in 2K x 18 TDP read-only mode (16 data + 2
ignored parity bits per address; 2048 entries per BRAM).  Multiple
BRAMs cascaded by a registered bsel mux on the upper address bits.
Read latency is one cycle (DOA_REG=0) — same as the inferred
$readmemh+sync-read pattern, so the FSM in smollm_layer needs only the
existing 1-cycle pipeline (e.g. NM_LOAD: addr → next-cycle data).

usage: gen_brom_sv.py <in.hex> <out.sv> <module_name>
"""
import sys, os

ENTRIES_PER_BRAM = 2048           # 2K × 18 mode
BITS_PER_DATA    = 16
BITS_PER_INIT    = 256            # one INIT_xx string covers 256 storage bits
ENTRIES_PER_INIT = BITS_PER_INIT // BITS_PER_DATA   # 16 entries per INIT_xx
N_INIT_PER_BRAM  = ENTRIES_PER_BRAM // ENTRIES_PER_INIT   # 128 INIT_xx (00..7F)


def read_hex(path: str) -> list[int]:
    out = []
    with open(path) as f:
        for line in f:
            line = line.split('//')[0].strip()
            if not line: continue
            out.append(int(line, 16) & 0xFFFF)
    return out


def init_strings(slab: list[int]) -> list[str]:
    """Return 128 INIT_00..INIT_7F strings (256-bit hex each) for one BRAM."""
    assert len(slab) == ENTRIES_PER_BRAM
    out = []
    for i in range(N_INIT_PER_BRAM):
        words = slab[i * ENTRIES_PER_INIT : (i + 1) * ENTRIES_PER_INIT]
        v = 0
        for j, w in enumerate(words):
            v |= (w & 0xFFFF) << (j * BITS_PER_DATA)
        out.append(f"{v:064X}")
    return out


def emit_ramb36(name: str, inits: list[str], indent="  ") -> list[str]:
    """Emit one RAMB36E1 #(...) i_<name> (...) instance in 2K x 18 TDP
    read-only mode.  addr_11 is an 11-bit address signal name; douta is
    a 32-bit wire receiving DOADO."""
    L = []
    L.append(f"{indent}RAMB36E1 #(")
    L.append(f'{indent}  .RAM_MODE("TDP"),')
    L.append(f"{indent}  .READ_WIDTH_A(18),")
    L.append(f"{indent}  .WRITE_WIDTH_A(0),")
    L.append(f"{indent}  .READ_WIDTH_B(0),")
    L.append(f"{indent}  .WRITE_WIDTH_B(0),")
    L.append(f"{indent}  .DOA_REG(0),")
    L.append(f"{indent}  .DOB_REG(0),")
    L.append(f'{indent}  .EN_ECC_READ("FALSE"),')
    L.append(f'{indent}  .EN_ECC_WRITE("FALSE"),')
    L.append(f'{indent}  .RAM_EXTENSION_A("NONE"),')
    L.append(f'{indent}  .RAM_EXTENSION_B("NONE"),')
    L.append(f'{indent}  .SIM_DEVICE("7SERIES"),')
    L.append(f"{indent}  .INIT_A(36'h0), .INIT_B(36'h0),")
    L.append(f"{indent}  .SRVAL_A(36'h0), .SRVAL_B(36'h0),")
    for i, s in enumerate(inits):
        L.append(f"{indent}  .INIT_{i:02X}(256'h{s}),")
    for i in range(16):
        comma = "," if i < 15 else ""
        L.append(f"{indent}  .INITP_{i:02X}(256'h0){comma}")
    L.append(f"{indent}) i_{name} (")
    L.append(f"{indent}  .CLKARDCLK(clk), .CLKBWRCLK(clk),")
    L.append(f"{indent}  .ENARDEN(1'b1), .ENBWREN(1'b0),")
    L.append(f"{indent}  .REGCEAREGCE(1'b1), .REGCEB(1'b0),")
    L.append(f"{indent}  .RSTRAMARSTRAM(1'b0), .RSTRAMB(1'b0),")
    L.append(f"{indent}  .RSTREGARSTREG(1'b0), .RSTREGB(1'b0),")
    L.append(f"{indent}  .CASCADEINA(1'b0), .CASCADEINB(1'b0),")
    L.append(f"{indent}  .INJECTSBITERR(1'b0), .INJECTDBITERR(1'b0),")
    L.append(f"{indent}  // 2Kx18 mode: ADDRARDADDR[14:4] = addr; [3:0] tied 0;")
    L.append(f"{indent}  // bit[15] tied 1 (no cascade).")
    L.append(f"{indent}  .ADDRARDADDR({{1'b1, {name}_addr_11, 4'b0}}),")
    L.append(f"{indent}  .ADDRBWRADDR(16'h8000),")
    L.append(f"{indent}  .DIADI(32'b0), .DIPADIP(4'b0),")
    L.append(f"{indent}  .DIBDI(32'b0), .DIPBDIP(4'b0),")
    L.append(f"{indent}  .WEA(4'b0), .WEBWE(8'b0),")
    L.append(f"{indent}  .DOADO({name}_dout), .DOPADOP(),")
    L.append(f"{indent}  .DOBDO(), .DOPBDOP(),")
    # Unused outputs — tied off to silence Vivado Synth 8-7023 warnings.
    L.append(f"{indent}  .CASCADEOUTA(), .CASCADEOUTB(),")
    L.append(f"{indent}  .DBITERR(), .ECCPARITY(),")
    L.append(f"{indent}  .RDADDRECC(), .SBITERR()")
    L.append(f"{indent});")
    return L


def gen_module(entries: list[int], mod_name: str, mem_file: str) -> str:
    N    = len(entries)
    aw   = max((N - 1).bit_length(), 11)   # ≥ 11 (one BRAM addr width)
    nbr  = (N + ENTRIES_PER_BRAM - 1) // ENTRIES_PER_BRAM
    bsel = max((nbr - 1).bit_length(), 1)

    L = []
    L.append(f"// AUTO-GENERATED by host/gen_brom_sv.py — do not edit.")
    L.append(f"// {N} entries × 16-bit, packed into {nbr} × RAMB36E1 (2K×18 mode).")
    L.append(f"// Read latency: 1 cycle (addr presented at clk edge T,")
    L.append(f"// data available at T+1).")
    L.append(f"")
    L.append(f"`default_nettype none")
    L.append(f"")
    L.append(f"module {mod_name} (")
    L.append(f"  input  wire             clk,")
    L.append(f"  input  wire [{aw-1:>2}:0]   addr,")
    L.append(f"  output wire [15:0]      data")
    L.append(f");")
    L.append(f"")
    L.append(f"  // Sim flow picks up sim/ramb36e1_stub.sv (gated on `VERILATOR`)")
    L.append(f"  // which models the same 2K x 18 read-only behaviour Vivado uses.")
    L.append(f"  // No `ifdef branching here so simulation and synthesis exercise")
    L.append(f"  // the identical wrapper logic.")
    L.append(f"")

    # One 32-bit DOADO per BRAM
    for b in range(nbr):
        L.append(f"  wire [31:0] b{b}_dout;")
        L.append(f"  wire [10:0] b{b}_addr_11 = addr[10:0];")

    L.append(f"")
    # Emit RAMB36E1 instances
    for b in range(nbr):
        slab = entries[b*ENTRIES_PER_BRAM : (b+1)*ENTRIES_PER_BRAM]
        slab = slab + [0] * (ENTRIES_PER_BRAM - len(slab))
        L.extend(emit_ramb36(f"b{b}", init_strings(slab)))
        L.append("")

    if nbr == 1:
        L.append(f"  assign data = b0_dout[15:0];")
    else:
        # Register the upper-bits BRAM-select to align with the 1-cycle
        # BRAM read latency, then comb-mux the appropriate b<N>_dout.
        L.append(f"  reg [{bsel-1}:0] bsel_r;")
        L.append(f"  always @(posedge clk) bsel_r <= addr[{aw-1}:11];")
        L.append(f"  reg [15:0] data_r;")
        L.append(f"  always @* begin")
        L.append(f"    case (bsel_r)")
        for b in range(nbr):
            L.append(f"      {bsel}'d{b}: data_r = b{b}_dout[15:0];")
        L.append(f"      default: data_r = 16'h0;")
        L.append(f"    endcase")
        L.append(f"  end")
        L.append(f"  assign data = data_r;")

    L.append(f"")
    L.append(f"endmodule")
    L.append(f"")
    L.append(f"`default_nettype wire")
    return "\n".join(L)


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    in_hex, out_sv, mod_name = sys.argv[1], sys.argv[2], sys.argv[3]
    entries = read_hex(in_hex)
    sv = gen_module(entries, mod_name, os.path.basename(in_hex))
    os.makedirs(os.path.dirname(out_sv) or ".", exist_ok=True)
    with open(out_sv, "w") as f:
        f.write(sv)
    n_bram = (len(entries) + ENTRIES_PER_BRAM - 1) // ENTRIES_PER_BRAM
    print(f"  {mod_name}: {len(entries)} entries → {n_bram} × RAMB36E1 → {out_sv}")


if __name__ == "__main__":
    main()
