// AUTO-GENERATED by host/gen_full_test.py — do not edit.
// NL=3 D=128 VOCAB=128 pos=3 in_token=37

localparam int FULL_NL       = 3;
localparam int FULL_D        = 128;
localparam int FULL_VOCAB    = 128;
localparam int FULL_POS      = 3;
localparam int FULL_IN_TOKEN = 37;
