// AUTO-GENERATED by host/gen_layer_test.py — do not edit.
// D=576 H_Q=9 H_KV=3 HD=64 FFN=1536 MAX_CTX=4 pos=3
// Weights/scales/γ/hidden_in/kv_cache live in matching .hex files
// ($readmemh into unpacked arrays — avoids Vivado segfault on huge packed selects).

localparam int LAYER_POS = 3;
