// Auto-generated by gen_layer_ddr3.py — do not edit.
// Per-matrix DDR3 byte offsets for the layer-test image.
// Pass these to smollm_layer's BASE_* parameters.

`define MICROGPT_LAYER_BASE_Q  30'h00000000
`define MICROGPT_LAYER_BASE_K  30'h00052000
`define MICROGPT_LAYER_BASE_V  30'h0006e000
`define MICROGPT_LAYER_BASE_O  30'h0008a000
`define MICROGPT_LAYER_BASE_GATE  30'h000dc000
`define MICROGPT_LAYER_BASE_UP  30'h001b4000
`define MICROGPT_LAYER_BASE_DOWN  30'h0028c000
`define MICROGPT_LAYER_DDR3_ENTRIES 222208
