// AUTO-GENERATED by host/gen_matvec_selftest.py — do not edit.
// 16-lane Q1.15 scale ROM, packed lane 0 in [15:0] .. lane 15 in [255:240].

localparam logic [255:0] SCALE_PACKED_INIT = 256'he4c4_e4f3_f41e_f1e8_f2ea_0271_f337_1f2d_1b73_fbce_1000_01bb_f0ee_12df_e34c_101c;
