// rope.sv — Rotary positional encoding (LLaMA / SmolLM2 convention).
//
// For HEAD_DIM = D, H2 = D/2:
//   freq[j]  = 1 / theta^(2j/D),  j = 0..H2-1
//   angle[j] = pos * freq[j]
//   y[j]     = x[j]    * cos(angle[j]) - x[j+H2] * sin(angle[j])   (j < H2)
//   y[j+H2]  = x[j+H2] * cos(angle[j]) + x[j]    * sin(angle[j])   (j < H2)
//
// Sin/cos computed on-demand via cordic_sincos — no 256 KB BRAM LUTs.
// Frequency table rope_freq_turns.svh holds FREQ_TURNS_Q31[j] = round(freq[j]/(2pi)*2^31).
//
// Operation:
//   Phase 1 (S_LOAD):   Accept HEAD_DIM input samples into xmem.
//                       Simultaneously run HEAD_DIM/2 CORDIC calls, storing
//                       results in cos_buf[j] / sin_buf[j], j=0..31.
//   Phase 2 (S_OUTPUT): All inputs and all CORDIC results ready.
//                       Output 64 beats in sequential order 0..HEAD_DIM-1,
//                       using a single out_cnt counter (same as original LUT design).
//   Phase 3 (S_DONE):   Pulse done.
//
// The two phases overlap: CORDIC computation runs during S_LOAD (input phase).
// For HEAD_DIM=64: 32 pairs × ~20 cycles each = ~640 cycles for CORDIC;
// inputs take 64 cycles and finish well before CORDIC.  S_OUTPUT starts when
// BOTH are done (~645 cycles), then 64 output beats, total ~710 cycles.
//
// Streaming protocol: identical to the original LUT-based rope.sv.
//   - drive pos, pulse start
//   - drive HEAD_DIM in_x samples with in_valid
//   - HEAD_DIM out_y / out_valid beats emitted sequentially
//   - done pulses one cycle after last out beat
//
// Synthesizable: no real / $sin / $cos / $pow / int in always_ff.

`default_nettype none

module rope #(
  parameter int  HEAD_DIM = 64,
  parameter int  MAX_CTX  = 2048,
  parameter real BASE_R   = 10000.0   // kept for interface compatibility; unused
)(
  input  wire                                clk,
  input  wire                                rst,

  input  wire                                start,
  input  wire [$clog2(MAX_CTX)-1:0]          pos,

  input  wire signed [15:0]                  in_x,
  input  wire                                in_valid,

  output logic signed [15:0]                 out_y,
  output logic                               out_valid,
  output logic                               done
);

  // -----------------------------------------------------------------------
  localparam int H   = HEAD_DIM;      // 64
  localparam int H2  = HEAD_DIM / 2;  // 32
  localparam int ICW = $clog2(H  + 1); // 7 bits, counts 0..H
  localparam int PCW = $clog2(H2 + 1); // 6 bits, counts 0..H2
  localparam int OCW = $clog2(H  + 1); // 7 bits, counts 0..H (out_cnt)

  // -----------------------------------------------------------------------
  // Angle conversion.
  // FREQ_TURNS_Q31[j] = round(freq[j]/(2pi) * 2^31).
  // t = pos * FREQ_TURNS_Q31[j]  (43-bit product).
  // ang_turns = $signed(t[30:0])  — Q0.31 signed, represents actual_turns × 2^31,
  //             range [-0.5, 0.5) turns (mod-1 reduction implicit in bit truncation).
  // angle_q3_27 = (ang_turns * PI_OVER_8_Q29) >>> 29
  //   because: angle_rad = turns × 2pi; angle_q3_27 = angle_rad × 2^27
  //     = (ang_turns/2^31) × 2pi × 2^27 = ang_turns × (pi/8 × 2^29) / 2^29.
  //   PI_OVER_8_Q29 = round(pi/8 × 2^29) = 210828714 = PI_HALF_Q27 of cordic_sincos.
  localparam logic signed [30:0] PI_OVER_8_Q29 = 31'sd210828714;

  // -----------------------------------------------------------------------
  // Frequency table (auto-generated by gen_rope_freq_table.py).
`include "rope_freq_turns.svh"

  // -----------------------------------------------------------------------
  // Buffers.
  logic signed [15:0] xmem   [0:H -1];   // input samples
  logic signed [15:0] cos_buf[0:H2-1];   // cos(angle[j]) Q1.15
  logic signed [15:0] sin_buf[0:H2-1];   // sin(angle[j]) Q1.15

  // -----------------------------------------------------------------------
  // Registered position (captured at start pulse).
  logic [10:0] reg_pos;

  // -----------------------------------------------------------------------
  // CORDIC tracking.
  //   cord_pair    — pair index of the currently running CORDIC call (0..H2-1).
  //                  Used to drive cord_angle combinatorially; stable from when
  //                  cord_start is asserted until cord_valid fires.
  //   cord_submit  — number of CORDIC calls issued so far (0..H2).
  //   cord_done    — number of CORDIC results stored in cos/sin_buf (0..H2).
  //   cord_busy    — 1 while a CORDIC call is in flight.
  logic [PCW-1:0] cord_pair;
  logic [PCW-1:0] cord_submit;
  logic [PCW-1:0] cord_done;
  logic           cord_busy;

  // CORDIC signals.
  logic               cord_start;
  logic signed [30:0] cord_angle;
  logic signed [15:0] cord_cos_out;
  logic signed [15:0] cord_sin_out;
  logic               cord_valid;

  // Combinatorial angle computation (uses cord_pair and reg_pos).
  logic [42:0]        ang_t43;
  logic signed [30:0] ang_turns;
  logic signed [61:0] ang_prod;

  always_comb begin : angle_comb
    // 43-bit product; upper bits are unused (only bottom 31 matter).
    ang_t43   = 43'(reg_pos) * {11'b0, FREQ_TURNS_Q31[cord_pair[4:0]]};
    ang_turns = $signed(ang_t43[30:0]);          // Q0.31 signed
    ang_prod  = ang_turns * PI_OVER_8_Q29;       // 62-bit signed
    // >>> 29: take bits[59:29] of ang_prod for 31-bit Q3.27 result.
    cord_angle = ang_prod[59:29];
  end

  cordic_sincos i_cordic (
    .clk      ( clk          ),
    .rst      ( rst          ),
    .start    ( cord_start   ),
    .angle_in ( cord_angle   ),
    .cos_out  ( cord_cos_out ),
    .sin_out  ( cord_sin_out ),
    .valid    ( cord_valid   )
  );

  // -----------------------------------------------------------------------
  // mac_q15 — (a × p) ± (b × q) → Q1.15 saturated.
  function automatic logic signed [15:0] mac_q15 (
    input logic signed [15:0] a, p, b, q,
    input logic               sign_neg
  );
    logic signed [31:0] pa, qb;
    logic signed [32:0] sum, sh;
    pa  = a * p;
    qb  = b * q;
    sum = sign_neg ? ({pa[31],pa} - {qb[31],qb}) : ({pa[31],pa} + {qb[31],qb});
    sh  = sum >>> 15;
    if      (sh > 33'sh00007FFF) mac_q15 = 16'sh7FFF;
    else if (sh < -33'sd32768)   mac_q15 = -16'sd32768;
    else                         mac_q15 = sh[15:0];
  endfunction

  // -----------------------------------------------------------------------
  // FSM.
  // States:
  //   S_IDLE    — wait for start.
  //   S_LOAD    — accept H input samples into xmem; concurrently compute all
  //               H2 CORDIC pairs and store in cos/sin_buf.
  //               Transitions to S_OUTPUT when both xmem and cos/sin_buf are full.
  //   S_OUTPUT  — stream 64 beats in sequential order out_cnt=0..H-1.
  //   S_DONE    — assert done for one cycle, then back to S_IDLE.
  //
  // CORDIC sequencing in S_LOAD:
  //   When !cord_busy && cord_submit < H2: assert cord_start, increment cord_submit.
  //   cord_pair is set to the pair index BEFORE asserting cord_start so that
  //   cord_angle (combinatorial) is stable on the cycle cord_start=1 AND the
  //   following cycle (S_FOLD in CORDIC reads angle_in).
  //   Specifically: at edge N, FSM sets cord_pair<=new_j AND cord_start<=1.
  //   At edge N+1: cord_pair=new_j, cord_start=1, cord_angle=f(reg_pos, new_j). ✓
  //   CORDIC S_FOLD at edge N+2 also reads cord_angle=f(reg_pos, new_j). ✓

  typedef enum logic [1:0] {S_IDLE, S_LOAD, S_OUTPUT, S_DONE} state_t;
  state_t state;

  logic [ICW-1:0] in_cnt;           // number of inputs received (0..H)
  logic           inputs_loaded;    // all H samples in xmem
  logic [OCW-1:0] out_cnt;          // sequential output counter (0..H-1)

  // Transition condition: all CORDIC done AND all inputs loaded.
  wire all_ready = inputs_loaded && (cord_done == PCW'(H2));

  always_ff @(posedge clk) begin
    if (rst) begin
      state         <= S_IDLE;
      in_cnt        <= '0;
      inputs_loaded <= 1'b0;
      cord_pair     <= '0;
      cord_submit   <= '0;
      cord_done     <= '0;
      cord_busy     <= 1'b0;
      cord_start    <= 1'b0;
      out_cnt       <= '0;
      out_valid     <= 1'b0;
      done          <= 1'b0;
      out_y         <= '0;
      reg_pos       <= '0;
    end else begin
      cord_start <= 1'b0;
      out_valid  <= 1'b0;
      done       <= 1'b0;

      case (state)

        // ----------------------------------------------------------------
        S_IDLE: begin
          if (start) begin
            reg_pos       <= 11'(pos);
            in_cnt        <= '0;
            inputs_loaded <= 1'b0;
            cord_pair     <= '0;           // pair 0 will be launched in S_LOAD
            cord_submit   <= '0;
            cord_done     <= '0;
            cord_busy     <= 1'b0;
            out_cnt       <= '0;
            state         <= S_LOAD;
            // DO NOT launch CORDIC pair 0 here: reg_pos hasn't updated yet
            // (it's a registered assignment, takes effect NEXT cycle = first S_LOAD cycle).
            // Pair 0 launch happens in S_LOAD on the cycle cord_busy=0.
          end
        end

        // ----------------------------------------------------------------
        // S_LOAD: accept inputs and run CORDIC pairs concurrently.
        S_LOAD: begin
          // --- Input side ---
          if (in_valid && !inputs_loaded) begin
            xmem[in_cnt[5:0]] <= in_x;
            in_cnt            <= in_cnt + 1'b1;
            if (in_cnt == ICW'(H - 1)) inputs_loaded <= 1'b1;
          end

          // --- CORDIC launch ---
          // Launch next pair when CORDIC is idle and pairs remain.
          // cord_pair is set to cord_submit (the next pair index) at the same
          // clock edge as cord_start, so cord_angle sees the correct pair index
          // on the very next cycle (when cord_start FF output is 1 and CORDIC
          // is transitioning to S_FOLD).
          if (!cord_busy && cord_submit < PCW'(H2)) begin
            cord_pair   <= cord_submit;
            cord_start  <= 1'b1;
            cord_busy   <= 1'b1;
            cord_submit <= cord_submit + 1'b1;
          end

          // --- CORDIC result capture ---
          if (cord_valid) begin
            cos_buf[cord_done[4:0]] <= cord_cos_out;
            sin_buf[cord_done[4:0]] <= cord_sin_out;
            cord_done <= cord_done + 1'b1;
            cord_busy <= 1'b0;
          end

          // --- Transition to output phase ---
          if (all_ready) state <= S_OUTPUT;
        end

        // ----------------------------------------------------------------
        // S_OUTPUT: stream 64 beats in sequential order using out_cnt.
        // For out_cnt in [0, H2-1]:   y = x[out_cnt]   *cos[j] - x[out_cnt+H2]*sin[j]
        //                             where j = out_cnt.
        // For out_cnt in [H2, H-1]:  y = x[out_cnt]   *cos[j] + x[out_cnt-H2]*sin[j]
        //                             where j = out_cnt - H2.
        S_OUTPUT: begin
          begin : out_blk
            logic [4:0]           j5;
            logic signed [15:0]   cval, sval, xa, xb;
            logic signed [15:0]   result;
            if (out_cnt < OCW'(H2)) begin
              // First half: j = out_cnt
              j5   = out_cnt[4:0];
              cval = cos_buf[j5];
              sval = sin_buf[j5];
              xa   = xmem[out_cnt[5:0]];          // x[j]
              xb   = xmem[{1'b1, out_cnt[4:0]}];  // x[j+H2]
              result = mac_q15(xa, cval, xb, sval, 1'b1);  // xa*cos - xb*sin
            end else begin
              // Second half: j = out_cnt - H2
              j5   = out_cnt[4:0];                // out_cnt[4:0] = out_cnt - H2 (since H2=32=2^5)
              cval = cos_buf[j5];
              sval = sin_buf[j5];
              xb   = xmem[out_cnt[5:0]];          // x[out_cnt] = x[j+H2]
              xa   = xmem[{1'b0, out_cnt[4:0]}];  // x[j]
              result = mac_q15(xb, cval, xa, sval, 1'b0);  // xb*cos + xa*sin
            end
            out_y     <= result;
            out_valid <= 1'b1;
          end

          out_cnt <= out_cnt + 1'b1;
          if (out_cnt == OCW'(H - 1)) state <= S_DONE;
        end

        // ----------------------------------------------------------------
        S_DONE: begin
          done  <= 1'b1;
          state <= S_IDLE;
        end

        default: state <= S_IDLE;
      endcase
    end
  end

endmodule

`default_nettype wire
