// rope_freq_turns.svh — AUTO-GENERATED by gen_rope_freq_table.py
// freq_turns[j] = freq[j]/(2π) as Q0.31 unsigned 32-bit.
// HEAD_DIM=64, BASE=10000, j=0..31
//
// Verification (Python):
//   import math
//   for j in range(32):
//     freq = 1.0/(10000**(2*j/64))
//     print(round(freq/(2*math.pi)*(1<<31)))

localparam logic [31:0] FREQ_TURNS_Q31 [0:31] = '{
  32'd   341782638,  // j= 0  freq_turns=1.59154943e-01
  32'd   256300821,  // j= 1  freq_turns=1.19349370e-01
  32'd   192198501,  // j= 2  freq_turns=8.94994014e-02
  32'd   144128543,  // j= 3  freq_turns=6.71150829e-02
  32'd   108081160,  // j= 4  freq_turns=5.03292121e-02
  32'd    81049436,  // j= 5  freq_turns=3.77415847e-02
  32'd    60778503,  // j= 6  freq_turns=2.83021959e-02
  32'd    45577447,  // j= 7  freq_turns=2.12236526e-02
  32'd    34178264,  // j= 8  freq_turns=1.59154944e-02
  32'd    25630082,  // j= 9  freq_turns=1.19349370e-02
  32'd    19219850,  // j=10  freq_turns=8.94994009e-03
  32'd    14412854,  // j=11  freq_turns=6.71150815e-03
  32'd    10808116,  // j=12  freq_turns=5.03292121e-03
  32'd     8104944,  // j=13  freq_turns=3.77415866e-03
  32'd     6077850,  // j=14  freq_turns=2.83021946e-03
  32'd     4557745,  // j=15  freq_turns=2.12236540e-03
  32'd     3417826,  // j=16  freq_turns=1.59154925e-03
  32'd     2563008,  // j=17  freq_turns=1.19349360e-03
  32'd     1921985,  // j=18  freq_turns=8.94994009e-04
  32'd     1441285,  // j=19  freq_turns=6.71150628e-04
  32'd     1080812,  // j=20  freq_turns=5.03292307e-04
  32'd      810494,  // j=21  freq_turns=3.77415679e-04
  32'd      607785,  // j=22  freq_turns=2.83021946e-04
  32'd      455774,  // j=23  freq_turns=2.12236308e-04
  32'd      341783,  // j=24  freq_turns=1.59155112e-04
  32'd      256301,  // j=25  freq_turns=1.19349454e-04
  32'd      192199,  // j=26  freq_turns=8.94996338e-05
  32'd      144129,  // j=27  freq_turns=6.71152957e-05
  32'd      108081,  // j=28  freq_turns=5.03291376e-05
  32'd       81049,  // j=29  freq_turns=3.77413817e-05
  32'd       60779,  // j=30  freq_turns=2.83024274e-05
  32'd       45577   // j=31  freq_turns=2.12234445e-05
};
