// AUTO-GENERATED by host/gen_rope_selftest.py — do not edit.
// 64 x Q1.15 input vector, lane 0 at bits [15:0].

localparam logic [1023:0] ROPE_X_PACKED = 1024'hdf71a97417962d050f4d10bbbdec2c18ecb22d52e38f1a7a290b2d7d5faba1fbc933f7a9fb1dd519c094142d3d5b04e2eacd0e245114359176aded58d428e58ef6b5c5c2e5e716cee40b2056cda30244c689f2e32e79a8914c08bbd5f30f18344e91f9a4bb02258b0f97f693fa8752c034aa049ed88f0343e9b931205191e0c5;
localparam logic [10:0] ROPE_POS = 11'd137;
