// AUTO-GENERATED by host/gen_softmax_selftest.py — do not edit.
// 64 × Q1.15 input vector, lane 0 at bits [15:0] of the literal.

localparam logic [1023:0] SOFTMAX_X_PACKED = 1024'h8ab170cde8d1f32d7eb8fa140dffd8061005e76f2c8fb669127802a019cab93a2ca56d8e33ac3ec430e9ea8f8148524f1441b4d3fb26f4cfac058cbfd7b0d724ba3ce6a0cc55faae3c09fdf7f736194b814835871904e2ea0705418354034d7f1bccf8aac5e3e7dc2017bc6328c4c87ade1935a608cb62eb214559c9a4a9f684;
