# run.tcl — Vivado build script for vc707_microgpt_eth.
#
# Adapted from cva6/corev_apu/fpga/scripts/run_mining.tcl. Reuses the SGMII
# Ethernet stack (framing_top_sgmii + sgmii_soc + eth_mac_1g + dualmem) from
# the kaspad accelerator and the gig_ethernet_pcs_pma_0 IP project.

set project microgpt_eth

# Branch-local merge (picosoc branch): PICOSOC=1 builds the PicoSoC bring-up
# shell (vc707_picosoc_shell) — a slimmed source set (no engine / microgpt core
# / build_version gate / ILA) that shares this project + the synth/impl tail.
#   build:  PICOSOC=1 vivado -mode batch -source scripts/prologue.tcl -source scripts/run.tcl
set _picosoc [info exists ::env(PICOSOC)]
if {$_picosoc} { puts "INFO: PICOSOC=1 -> building vc707_picosoc_shell (bring-up shell)" }
# PICOSOC_ENGINE=1 -> the REAL engine top (vc707_microgpt_eth) with the PicoSoC
# front-end (picosoc_eth_bridge) replacing microgpt_eth_ctrl.  Lean base-fit.
set _picosoc_engine [info exists ::env(PICOSOC_ENGINE)]
if {$_picosoc_engine} { puts "INFO: PICOSOC_ENGINE=1 -> engine top + PicoSoC front-end" }

# Detect existing-project vs fresh-project so `make` can incrementally
# rebuild without re-adding sources (which Vivado errors on) and
# without choking on a stale failed run.  Signal: presence of the
# constraints file in any fileset.
set is_fresh [expr {[llength [get_files -quiet *microgpt_eth.xdc]] == 0}]
if {$is_fresh} {
    puts "INFO: fresh project — adding all sources/IPs/constraints"
} else {
    puts "INFO: existing project — incremental rebuild (skipping source-add)"
}

# Constraints
if {$is_fresh} {
    add_files -fileset constrs_1 -norecurse constraints/microgpt_eth.xdc
}

if {$_picosoc} {

# Shell-only constraints (UART pins) — added idempotently and OUTSIDE is_fresh
# so an already-created project picks them up without a wipe.  Kept separate
# from microgpt_eth.xdc because a conditional get_ports guard in the shared XDC
# proved unreliable (the pins ended up unconstrained -> UCIO-1 DRC failure).
if {[llength [get_files -quiet *picosoc.xdc]] == 0} {
    add_files -fileset constrs_1 -norecurse constraints/picosoc.xdc
}

# Self-heal the progmem case-ROM -> BRAM swap on an already-created project
# (read_verilog source-list edits only take effect on a fresh project, so an
# existing project would still reference the deleted progmem_shell.v).  For
# other source-set changes, `make wipe-project` is the clean reset.
if {[llength [get_files -quiet *progmem_shell.v]] > 0} {
    remove_files [get_files *progmem_shell.v]
}
if {[llength [get_files -quiet *progmem_bram.v]] == 0} {
    read_verilog src/soc/progmem_bram.v
}

# picosoc_noflash guards on PICORV32_REGS (and `errors if picorv32.v compiles
# first).  Set the macro globally on EVERY run (so an already-created project
# picks it up too, no wipe needed) — the guard is then bypassed regardless of
# Vivado's compile order, and picorv32 uses the picosoc_regs register file.
# PROGMEM_HEX points the BRAM progmem at the firmware .mem (absolute path; synth
# runs from a subdir).  The BRAM init is the default firmware; `make fw-update`
# later swaps it in the built .bit via updatemem (needs the .mmi from below).
set _fw_mem [file normalize src/soc/firmware_shell.mem]

# Integrated ILA (default ON; PICOSOC_ILA=0 disables).  Pre-generated by its own
# IP project (ip/picosoc_ila/, `make -C ip/picosoc_ila`, source tcl committed —
# same pattern as the engine ILAs) and read here via read_ip.  Probe widths come
# from that tcl and match i_ila in vc707_picosoc_shell.  The (* mark_debug *)
# shell nets are preserved regardless for "Set Up Debug".
set _ila [expr {![info exists ::env(PICOSOC_ILA)] || [string trim $::env(PICOSOC_ILA)] ne "0"}]

set _defs [list "PICORV32_REGS=picosoc_regs" "PROGMEM_HEX=\"$_fw_mem\""]
if {$_ila} { lappend _defs "PICOSOC_ILA" }
set_property verilog_define $_defs [current_fileset]

if {$_ila && [llength [get_ips -quiet picosoc_ila]] == 0} {
    read_ip { "ip/picosoc_ila/picosoc_ila.srcs/sources_1/ip/picosoc_ila/picosoc_ila.xci" }
}

# ===== PicoSoC bring-up shell source set (merged from run_picosoc.tcl) =====
if {$is_fresh} {
    read_ip { \
        "ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci" \
    }
    read_ip { \
        "ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.srcs/sources_1/ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.xci" \
    }
    set_property include_dirs [list "../src/include" "src" "src/soc"] [current_fileset]
    read_verilog -sv { \
        eth/axis_gmii_rx.sv \
        eth/axis_gmii_tx.sv \
        eth/dualmem_widen8.sv \
        eth/dualmem_widen.sv \
        eth/eth_mac_1g.sv \
        eth/framing_top_sgmii.sv \
        eth/rgmii_lfsr.sv \
        eth/sgmii_soc.sv \
    }
    read_verilog { \
        src/soc/picosoc_noflash.v \
        src/soc/picorv32.v \
        src/soc/simpleuart.v \
        src/soc/progmem_bram.v \
    }
    read_verilog -sv { \
        src/soc/soc_ddr_bridge.sv \
        src/soc/vc707_picosoc_shell.sv \
    }
    read_verilog -sv {src/vc707.svh}
    set _fobj [get_files -of_objects [get_filesets sources_1] [list "*src/vc707.svh"]]
    set_property -dict {file_type {Verilog Header} is_global_include 1} -objects $_fobj
    set_property top vc707_picosoc_shell [current_fileset]
}

} else {

# Absolute path to the weight ROM .hex files. Vivado runs synth from
# microgpt_eth.runs/synth_1/, where a relative "generated" path can't be
# found, so we burn the absolute path into a Verilog macro consumed by
# microgpt_exact_core_rom_init.svh.
set abs_weight_dir [file normalize ../generated]
# `MICROGPT_DDR3_WEIGHTS` selects weight_streamer_mt + AXI master in
# smollm_layer (replacing the BRAM-only weight_streamer_brom path).
# Build define list — the int8 multilayer path needs DDR3 streaming + ILA
# probes + LAYER_DEBUG; the block-FP path uses BRAM weights and has no ILA
# probe set, so those defines are dropped (and MICROGPT_USE_BFP is added).
# Toggled via the USE_BFP=1 Makefile knob (env var VIVADO_DEFINES).
set _use_bfp 0
set _bfp_stream 0
if {[info exists ::env(VIVADO_DEFINES)]} {
    foreach d $::env(VIVADO_DEFINES) {
        if {$d eq "MICROGPT_USE_BFP"}     { set _use_bfp 1 }
        if {$d eq "MICROGPT_BFP_STREAM"}  { set _bfp_stream 1 }
    }
}
if {$_use_bfp} {
    set _defs [list \
        "MICROGPT_WEIGHT_DIR=\"$abs_weight_dir\"" \
        "MICROGPT_NO_OP_TESTS" \
        "MICROGPT_USE_BFP" \
    ]
    if {$_bfp_stream} {
        puts "INFO: build defines = block-FP path + DDR3 streaming (USE_BFP=1 BFP_STREAM=1)"
        lappend _defs "MICROGPT_BFP_STREAM"
    } else {
        puts "INFO: build defines = block-FP path (USE_BFP=1)"
    }
    set_property verilog_define $_defs [current_fileset]
} else {
    puts "INFO: build defines = int8 multilayer path (default)"
    set_property verilog_define [list \
        "MICROGPT_WEIGHT_DIR=\"$abs_weight_dir\"" \
        "MICROGPT_DDR3_WEIGHTS" \
        "MICROGPT_ILA" \
        "MICROGPT_NO_OP_TESTS" \
        "MICROGPT_LAYER_DEBUG" \
    ] [current_fileset]
}

# PicoSoC front-end (PICOSOC_ENGINE): append the SoC defines to whatever the
# engine path set above.  picosoc_noflash needs PICORV32_REGS; the BRAM progmem
# needs PROGMEM_HEX (firmware_engine.mem); vc707_microgpt_eth swaps eth_ctrl
# for picosoc_eth_bridge under PICOSOC_ENGINE.
if {$_picosoc_engine} {
    set _d [get_property verilog_define [current_fileset]]
    lappend _d "PICOSOC_ENGINE" "PICORV32_REGS=picosoc_regs" \
               "PROGMEM_HEX=\"[file normalize src/soc/firmware_engine.mem]\""
    set_property verilog_define $_d [current_fileset]
    puts "INFO: PICOSOC_ENGINE — SoC front-end defines appended"
}

# build_version.svh (BUILD_VERSION = git HEAD short hash) is generated BEFORE
# synth by the Makefile prereq `host/gen_build_version.py`, which also runs the
# clean-tree gate (refuses uncommitted Verilog; ALLOW_DIRTY=1 to override).
# That keeps a single generator and lets the gate fail fast before Vivado.
# Here we only verify it exists and echo it, so a raw `vivado -source run.tcl`
# (outside make) fails loudly instead of synthesising a stale/garbage version.
set _bv_path "../generated/build_version.svh"
if {![file exists $_bv_path]} {
    error "ERROR: $_bv_path missing — build via 'make' (which runs host/gen_build_version.py), not raw run.tcl"
}
set _bv_fh [open $_bv_path r]
puts "build_version.svh: [string trim [read $_bv_fh]]"
close $_bv_fh

if {$is_fresh} {

# PCS/PMA IP — pre-generated under ip/gig_ethernet_pcs_pma_0/
read_ip { \
    "ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci" \
}

# MIG DDR3 IP — pre-generated under ip/xlnx_mig_7_ddr3/
read_ip { \
    "ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.srcs/sources_1/ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.xci" \
}

# ILA debug IPs (gated by `MICROGPT_ILA in vc707_microgpt_eth.sv).
# Generated by `make -C ip/microgpt_ila_{core,axi}` before the main flow.
if {[file exists "ip/microgpt_ila_core/microgpt_ila_core.srcs/sources_1/ip/microgpt_ila_core/microgpt_ila_core.xci"]} {
  read_ip { \
      "ip/microgpt_ila_core/microgpt_ila_core.srcs/sources_1/ip/microgpt_ila_core/microgpt_ila_core.xci" \
      "ip/microgpt_ila_axi/microgpt_ila_axi.srcs/sources_1/ip/microgpt_ila_axi/microgpt_ila_axi.xci" \
  }
}

}  ;# end is_fresh (read_ip)

# Include dirs — microgpt core uses src/include/, eth uses src/ for vc707.svh
set abs_generated [file normalize ../generated]
set_property include_dirs [list \
    "../src/include" \
    "src" \
    "src/smollm" \
    "src/soc" \
    $abs_generated \
] [current_fileset]

if {$is_fresh} {

# Ethernet MAC and framing (copied from cva6-ethernet)
read_verilog -sv { \
    eth/axis_gmii_rx.sv \
    eth/axis_gmii_tx.sv \
    eth/dualmem_widen8.sv \
    eth/dualmem_widen.sv \
    eth/eth_mac_1g.sv \
    eth/framing_top_sgmii.sv \
    eth/rgmii_lfsr.sv \
    eth/sgmii_soc.sv \
}

# PicoSoC front-end (PICOSOC_ENGINE): drop-in for microgpt_eth_ctrl.
if {$_picosoc_engine} {
    read_verilog { \
        src/soc/picosoc_noflash.v \
        src/soc/picorv32.v \
        src/soc/simpleuart.v \
        src/soc/progmem_bram.v \
    }
    read_verilog -sv { src/soc/picosoc_eth_bridge.sv }
}

# microgpt BabyGPT core (used by vc707_microgpt_eth's microgpt_exact_core
# instance — small char-level GPT, predates the SmolLM2 stack).  Stays.
read_verilog -sv { \
    ../src/microgpt_categorical_sampler.sv \
    ../src/microgpt_exact_core.sv \
    ../src/rms_scale_engine.sv \
    ../src/sat_div16_engine.sv \
    ../src/systolic_matvec16_tile.sv \
}

# VC707 top + Ethernet bridge + DDR3 weight tile cache + DDR3 write master
# + SmolLM2 single-op selftests (small D=64 BRAMs) + BFP autoregress stack.
#
# Retired sources (the int8 SmolLM2 multilayer chain — 23040 × 16 caches
# whose awkward depth was hanging Vivado's memory inferencer):
#   smollm_layer.sv, smollm_multilayer_tm.sv,
#   smollm_layer_selftest.sv, smollm_multilayer_tm_selftest.sv,
#   matvec_int8_engine.sv, weight_streamer_brom.sv, weight_streamer_mt.sv,
#   factor_ram.sv.
# Their op-selftest siblings (matvec_selftest, rmsnorm_selftest, ...) and
# the leaf modules they rely on (rmsnorm/rope/swiglu/softmax_q15) stay
# because vc707_microgpt_eth still instantiates the per-op selftests.
read_verilog -sv { \
    src/microgpt_eth_ctrl.sv \
    src/weight_stream_axi.sv \
    src/weight_tile_cache.sv \
    src/ddr_write_master.sv \
    src/vc707_microgpt_eth.sv \
    src/smollm/cordic_sincos.sv \
    src/smollm/matvec_int8_engine.sv \
    src/smollm/matvec_selftest.sv \
    src/smollm/rmsnorm.sv \
    src/smollm/rmsnorm_selftest.sv \
    src/smollm/rope.sv \
    src/smollm/rope_selftest.sv \
    src/smollm/swiglu.sv \
    src/smollm/swiglu_selftest.sv \
    src/smollm/softmax_q15.sv \
    src/smollm/softmax_selftest.sv \
    src/smollm/matvec_bfp_engine.sv \
    src/smollm/rmsnorm_bfp.sv \
    src/smollm/rope_bfp.sv \
    src/smollm/swiglu_bfp.sv \
    src/smollm/softmax_bfp.sv \
    src/smollm/residual_bfp.sv \
    src/smollm/bfp_sdpram.sv \
    src/smollm/bfp_sdpram_striped.sv \
    src/smollm/bfp_sdpram_packed.sv \
    src/smollm/bfp_sdpram_packed_pr.sv \
    src/smollm/weight_streamer_bfp_mt.sv \
    src/smollm/smollm_layer_bfp.sv \
    src/smollm/embed_lookup_bfp.sv \
    src/smollm/smollm_multilayer_tm_bfp.sv \
    src/smollm/smollm_decode_head_bfp.sv \
    src/smollm/autoregress_bfp_top.sv \
}

# Generated brom_*.sv wrappers — explicit RAMB36E1 instances for the
# per-layer scale/gamma ROMs.  Emitted by host/gen_brom_sv.py from the
# corresponding tm_layer_<NAME>.hex (rebuilt by the top-level Makefile).
read_verilog -sv [glob -nocomplain ../generated/brom_*.sv]

# Board-specific header (defines `VC707 for dualmem_widen BRAM config)
read_verilog -sv {src/vc707.svh}
set file "src/vc707.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -dict { file_type {Verilog Header} is_global_include 1} -objects $file_obj

set_property top vc707_microgpt_eth [current_fileset]

}  ;# end is_fresh (read_verilog block)

}  ;# end if {$_picosoc} ... else (source/IP/top setup)

update_compile_order -fileset sources_1

# Reset any non-success synth_1 / impl_1 so launch_runs can proceed
# (Vivado refuses to relaunch a run in Error / Aborted state and the
# old `make` flow used to nuke the project to sidestep this).
foreach run_name {synth_1 impl_1} {
    if {[llength [get_runs -quiet $run_name]] > 0} {
        set st [get_property STATUS [get_runs $run_name]]
        if {!([string match -nocase "*Complete*" $st]
              && ![string match -nocase "*Error*" $st])} {
            puts "INFO: resetting $run_name (was: $st)"
            reset_run $run_name
        }
    }
}

synth_design -rtl -name rtl_1

# Retiming disabled — when on, Vivado was free to slide registers across
# the matvec_int8_engine wide multiplier (acc_r * scale_q15) and produced
# wrong matvec outputs (saturation applied to a partial product).  Keep
# off until we add explicit pipeline stages to that path.
# set_property STEPS.SYNTH_DESIGN.ARGS.RETIMING true [get_runs synth_1]

launch_runs synth_1
wait_on_run synth_1
open_run synth_1

exec mkdir -p reports/
exec rm -rf reports/*

check_timing -verbose                                                   -file reports/$project.check_timing.rpt
report_timing -max_paths 100 -nworst 100 -delay_type max -sort_by slack -file reports/$project.timing_WORST_100.rpt
report_timing -nworst 1 -delay_type max -sort_by group                  -file reports/$project.timing.rpt
report_utilization -hierarchical                                        -file reports/$project.utilization.rpt
report_cdc                                                              -file reports/$project.cdc.rpt
report_clock_interaction                                                -file reports/$project.clock_interaction.rpt

launch_runs impl_1
wait_on_run impl_1
launch_runs impl_1 -to_step write_bitstream
wait_on_run impl_1
open_run impl_1

if {$_picosoc} {
    # BRAM memory-map for firmware swaps via updatemem (make fw-update): lets us
    # patch the progmem in the built .bit without re-synthesis.
    write_mem_info -force picosoc_shell.mmi
    puts "INFO: wrote picosoc_shell.mmi (progmem BRAM map for updatemem)"
}

exec mkdir -p reports/
exec rm -rf reports/*
check_timing                                                              -file reports/${project}.check_timing.rpt
report_timing -max_paths 100 -nworst 100 -delay_type max -sort_by slack   -file reports/${project}.timing_WORST_100.rpt
report_timing -nworst 1 -delay_type max -sort_by group                    -file reports/${project}.timing.rpt
report_utilization -hierarchical                                          -file reports/${project}.utilization.rpt
