# run.tcl — Vivado build script for vc707_microgpt_eth.
#
# Adapted from cva6/corev_apu/fpga/scripts/run_mining.tcl. Reuses the SGMII
# Ethernet stack (framing_top_sgmii + sgmii_soc + eth_mac_1g + dualmem) from
# the kaspad accelerator and the gig_ethernet_pcs_pma_0 IP project.

set project microgpt_eth

# Constraints
add_files -fileset constrs_1 -norecurse constraints/microgpt_eth.xdc

# Absolute path to the weight ROM .hex files. Vivado runs synth from
# microgpt_eth.runs/synth_1/, where a relative "generated" path can't be
# found, so we burn the absolute path into a Verilog macro consumed by
# microgpt_exact_core_rom_init.svh.
set abs_weight_dir [file normalize ../generated]
# `MICROGPT_DDR3_WEIGHTS` selects weight_streamer_mt + AXI master in
# smollm_layer (replacing the BRAM-only weight_streamer_brom path).
# Build define list — the int8 multilayer path needs DDR3 streaming + ILA
# probes + LAYER_DEBUG; the block-FP path uses BRAM weights and has no ILA
# probe set, so those defines are dropped (and MICROGPT_USE_BFP is added).
# Toggled via the USE_BFP=1 Makefile knob (env var VIVADO_DEFINES).
set _use_bfp 0
if {[info exists ::env(VIVADO_DEFINES)]} {
    foreach d $::env(VIVADO_DEFINES) {
        if {$d eq "MICROGPT_USE_BFP"} { set _use_bfp 1 }
    }
}
if {$_use_bfp} {
    puts "INFO: build defines = block-FP path (USE_BFP=1)"
    set_property verilog_define [list \
        "MICROGPT_WEIGHT_DIR=\"$abs_weight_dir\"" \
        "MICROGPT_NO_OP_TESTS" \
        "MICROGPT_USE_BFP" \
    ] [current_fileset]
} else {
    puts "INFO: build defines = int8 multilayer path (default)"
    set_property verilog_define [list \
        "MICROGPT_WEIGHT_DIR=\"$abs_weight_dir\"" \
        "MICROGPT_DDR3_WEIGHTS" \
        "MICROGPT_ILA" \
        "MICROGPT_NO_OP_TESTS" \
        "MICROGPT_LAYER_DEBUG" \
    ] [current_fileset]
}

# Regenerate build_version.svh so BUILD_VERSION reflects this build's epoch.
# Done in Tcl (Vivado's bundled Python is stripped and can't run host scripts).
set _build_epoch [clock seconds]
set _build_low32 [format "%08x" [expr {$_build_epoch & 0xFFFFFFFF}]]
set _build_stamp [clock format $_build_epoch -format "%Y-%m-%d %H:%M:%S"]
set _bv_path "../generated/build_version.svh"
set _bv_fh [open $_bv_path w]
puts $_bv_fh "// AUTO-GENERATED by scripts/run.tcl — do not edit."
puts $_bv_fh "// Build time: $_build_stamp  (epoch $_build_epoch)"
puts $_bv_fh ""
puts $_bv_fh "localparam logic \[31:0\] BUILD_VERSION = 32'h$_build_low32;"
close $_bv_fh
puts "build_version.svh: BUILD_VERSION = 0x$_build_low32  ($_build_stamp)"

# PCS/PMA IP — pre-generated under ip/gig_ethernet_pcs_pma_0/
read_ip { \
    "ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci" \
}

# MIG DDR3 IP — pre-generated under ip/xlnx_mig_7_ddr3/
read_ip { \
    "ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.srcs/sources_1/ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.xci" \
}

# ILA debug IPs (gated by `MICROGPT_ILA in vc707_microgpt_eth.sv).
# Generated by `make -C ip/microgpt_ila_{core,axi}` before the main flow.
if {[file exists "ip/microgpt_ila_core/microgpt_ila_core.srcs/sources_1/ip/microgpt_ila_core/microgpt_ila_core.xci"]} {
  read_ip { \
      "ip/microgpt_ila_core/microgpt_ila_core.srcs/sources_1/ip/microgpt_ila_core/microgpt_ila_core.xci" \
      "ip/microgpt_ila_axi/microgpt_ila_axi.srcs/sources_1/ip/microgpt_ila_axi/microgpt_ila_axi.xci" \
  }
}

# Include dirs — microgpt core uses src/include/, eth uses src/ for vc707.svh
set abs_generated [file normalize ../generated]
set_property include_dirs [list \
    "../src/include" \
    "src" \
    "src/smollm" \
    $abs_generated \
] [current_fileset]

# Ethernet MAC and framing (copied from cva6-ethernet)
read_verilog -sv { \
    eth/axis_gmii_rx.sv \
    eth/axis_gmii_tx.sv \
    eth/dualmem_widen8.sv \
    eth/dualmem_widen.sv \
    eth/eth_mac_1g.sv \
    eth/framing_top_sgmii.sv \
    eth/rgmii_lfsr.sv \
    eth/sgmii_soc.sv \
}

# microgpt core (shared with the DE1-SoC build, sourced from ../src/)
read_verilog -sv { \
    ../src/microgpt_categorical_sampler.sv \
    ../src/microgpt_exact_core.sv \
    ../src/rms_scale_engine.sv \
    ../src/sat_div16_engine.sv \
    ../src/systolic_matvec16_tile.sv \
}

# VC707 top + Ethernet bridge + DDR3 weight tile cache + DDR3 write master
# + SmolLM2 building blocks (parse-validated; not yet wired into the top)
read_verilog -sv { \
    src/microgpt_eth_ctrl.sv \
    src/weight_stream_axi.sv \
    src/weight_tile_cache.sv \
    src/ddr_write_master.sv \
    src/vc707_microgpt_eth.sv \
    src/smollm/cordic_sincos.sv \
    src/smollm/matvec_int8_engine.sv \
    src/smollm/matvec_selftest.sv \
    src/smollm/rmsnorm.sv \
    src/smollm/rmsnorm_selftest.sv \
    src/smollm/rope.sv \
    src/smollm/rope_selftest.sv \
    src/smollm/swiglu.sv \
    src/smollm/swiglu_selftest.sv \
    src/smollm/softmax_q15.sv \
    src/smollm/softmax_selftest.sv \
    src/smollm/weight_streamer_brom.sv \
    src/smollm/weight_streamer_mt.sv \
    src/smollm/factor_ram.sv \
    src/smollm/smollm_layer.sv \
    src/smollm/smollm_layer_selftest.sv \
    src/smollm/smollm_multilayer_tm.sv \
    src/smollm/smollm_multilayer_tm_selftest.sv \
    src/smollm/matvec_bfp_engine.sv \
    src/smollm/rmsnorm_bfp.sv \
    src/smollm/rope_bfp.sv \
    src/smollm/swiglu_bfp.sv \
    src/smollm/softmax_bfp.sv \
    src/smollm/residual_bfp.sv \
    src/smollm/smollm_layer_bfp.sv \
    src/smollm/smollm_layer_bfp_selftest.sv \
}

# Generated brom_*.sv wrappers — explicit RAMB36E1 instances for the
# per-layer scale/gamma ROMs.  Emitted by host/gen_brom_sv.py from the
# corresponding tm_layer_<NAME>.hex (rebuilt by the top-level Makefile).
read_verilog -sv [glob -nocomplain ../generated/brom_*.sv]

# Board-specific header (defines `VC707 for dualmem_widen BRAM config)
read_verilog -sv {src/vc707.svh}
set file "src/vc707.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -dict { file_type {Verilog Header} is_global_include 1} -objects $file_obj

set_property top vc707_microgpt_eth [current_fileset]

update_compile_order -fileset sources_1

synth_design -rtl -name rtl_1

# Retiming disabled — when on, Vivado was free to slide registers across
# the matvec_int8_engine wide multiplier (acc_r * scale_q15) and produced
# wrong matvec outputs (saturation applied to a partial product).  Keep
# off until we add explicit pipeline stages to that path.
# set_property STEPS.SYNTH_DESIGN.ARGS.RETIMING true [get_runs synth_1]

launch_runs synth_1
wait_on_run synth_1
open_run synth_1

exec mkdir -p reports/
exec rm -rf reports/*

check_timing -verbose                                                   -file reports/$project.check_timing.rpt
report_timing -max_paths 100 -nworst 100 -delay_type max -sort_by slack -file reports/$project.timing_WORST_100.rpt
report_timing -nworst 1 -delay_type max -sort_by group                  -file reports/$project.timing.rpt
report_utilization -hierarchical                                        -file reports/$project.utilization.rpt
report_cdc                                                              -file reports/$project.cdc.rpt
report_clock_interaction                                                -file reports/$project.clock_interaction.rpt

launch_runs impl_1
wait_on_run impl_1
launch_runs impl_1 -to_step write_bitstream
wait_on_run impl_1
open_run impl_1

exec mkdir -p reports/
exec rm -rf reports/*
check_timing                                                              -file reports/${project}.check_timing.rpt
report_timing -max_paths 100 -nworst 100 -delay_type max -sort_by slack   -file reports/${project}.timing_WORST_100.rpt
report_timing -nworst 1 -delay_type max -sort_by group                    -file reports/${project}.timing.rpt
report_utilization -hierarchical                                          -file reports/${project}.utilization.rpt
