#!/usr/bin/env python3
"""Generate rope_freq_turns.svh — 32-entry Q0.31 frequency table for rope.sv CORDIC path.

For HEAD_DIM=64, BASE=10000, j=0..31:
  freq[j]        = 1 / BASE^(2j/HEAD_DIM)
  freq_turns[j]  = freq[j] / (2*pi)   (converts Hz → turns per token)

Stored as Q0.31 unsigned 32-bit (actual value × 2^31, round-to-nearest).
freq[0]=1 → freq_turns[0] ≈ 0.1592 → Q0.31 ≈ 342097056
freq[31]    → freq_turns[31] ≈ 2.12e-5 → Q0.31 ≈ 45505

Output: ../generated/rope_freq_turns.svh
  localparam logic [31:0] FREQ_TURNS_Q31 [0:31] = '{ ... };
"""

import argparse
import math
import os

ap = argparse.ArgumentParser()
ap.add_argument("--base", type=float, default=10000.0,
                help="rope_theta (10000 for original test, 100000 for SmolLM2)")
ap.add_argument("--head-dim", type=int, default=64)
args = ap.parse_args()

HEAD_DIM = args.head_dim
H2 = HEAD_DIM // 2
BASE = args.base
TWO_PI = 2.0 * math.pi

entries = []
for j in range(H2):
    freq_j = 1.0 / (BASE ** (2.0 * j / HEAD_DIM))
    freq_turns_j = freq_j / TWO_PI
    q31 = round(freq_turns_j * (1 << 31))
    assert 0 <= q31 <= 0xFFFFFFFF, f"j={j}: {q31} out of range"
    entries.append(q31)

# Write SVH
out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "generated")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "rope_freq_turns.svh")

with open(out_path, "w") as f:
    f.write("// rope_freq_turns.svh — AUTO-GENERATED by gen_rope_freq_table.py\n")
    f.write("// freq_turns[j] = freq[j]/(2π) as Q0.31 unsigned 32-bit.\n")
    f.write(f"// HEAD_DIM={HEAD_DIM}, BASE={BASE:.0f}, j=0..{H2-1}\n")
    f.write("//\n")
    f.write("// Verification (Python):\n")
    f.write("//   import math\n")
    f.write(f"//   for j in range({H2}):\n")
    f.write(f"//     freq = 1.0/({BASE:.0f}**(2*j/{HEAD_DIM}))\n")
    f.write("//     print(round(freq/(2*math.pi)*(1<<31)))\n")
    f.write("\n")
    f.write("localparam logic [31:0] FREQ_TURNS_Q31 [0:31] = '{\n")
    for i, v in enumerate(entries):
        comma = "," if i < H2 - 1 else " "
        f.write(f"  32'd{v:>12}{comma}  // j={i:2d}  freq_turns={v/(1<<31):.8e}\n")
    f.write("};\n")

print(f"wrote {out_path}")
for j, v in enumerate(entries):
    print(f"  j={j:2d}: {v:>12}  ({v/(1<<31):.8e} turns/token)")
