// tb_autoregress_bfp_stream.cpp — drives the BFP autoregress stack in
// streaming mode (STREAM_WEIGHTS=1, STREAM_LOOKUP=1) to completion and
// dumps the resulting token sequence.  Should produce identical tokens
// to the BRAM-mode tb_autoregress_bfp.  Diverging tokens flag a bug in
// the streamer / AXI handshake / FSM pipelining.
//
// Prerequisite: ../generated/lbfp_full_DDR3.hex generated by
//   LBFP_EMIT_HEX=1 python3 host/gen_smollm_blockfp_ddr.py

#include "Vtb_autoregress_bfp_stream.h"
#include "verilated.h"
#include <cstdio>
#include <cstdint>

static Vtb_autoregress_bfp_stream* d;
static uint64_t cycle = 0;
static void tick() { d->clk = 0; d->eval(); d->clk = 1; d->eval(); ++cycle; }

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);
  d = new Vtb_autoregress_bfp_stream;
  d->clk = 0; d->rst = 1; d->go = 0;
  d->eval();
  for (int i = 0; i < 8; ++i) tick();
  d->rst = 0; tick();
  d->go = 1; tick();
  d->go = 0;

  // Cycle ceiling — streaming adds ~1 cycle/beat × ~1500 chunks/token
  // × 19 tokens ≈ 30 M cycles, plus AXI handshake overhead.  Give 100×
  // headroom for slow CDC and exponent / RoPE LUT lookups.
  const uint64_t LIM = 5'000'000'000ULL;
  std::fprintf(stderr, "[tb_autoregress_bfp_stream] running streaming autoregress…\n");
  while (!d->done && cycle < LIM) {
    tick();
    if ((cycle % 10'000'000ULL) == 0)
      std::fprintf(stderr, "  ... @ cycle %llu\n", (unsigned long long)cycle);
  }
  if (cycle >= LIM) {
    std::fprintf(stderr, "TIMEOUT @ cycle %llu\n", (unsigned long long)cycle);
    delete d; return 1;
  }

  std::printf("RTL_TOKENS:");
  const int N_STEPS = 19;
  for (int i = 0; i < N_STEPS; ++i) {
    int word  = (i * 16) / 32;
    int shift = (i * 16) % 32;
    uint16_t tok = (d->result_tokens[word] >> shift) & 0xFFFF;
    std::printf(" %u", (unsigned)tok);
  }
  std::printf("\n");
  std::fprintf(stderr, "[tb_autoregress_bfp_stream] done @ cycle %llu\n",
               (unsigned long long)cycle);
  delete d; return 0;
}
