#!/usr/bin/env python3
"""bin2init.py — pack a firmware .bin into 4x RAMB16_S9_S9 byte-lane INIT params.

The progmem is 4 byte-lanes (RAMB16_S9_S9, each 2048 x 8+parity -> retargets to a
RAMB18E1).  Lane i holds byte i of every 32-bit word, so the CPU's mem_wstrb maps
straight to a per-lane write-enable (correct sb/sh/sw to instruction memory for
the self-modifying / ethernet-loaded overlay path).  4 lanes x 2048 = 2048 words
= 8 KB (2x the old single-RAMB36E1 progmem).

Each lane is 2048 x 8 -> INIT_00..INIT_3F (64 x 256-bit).  INIT_xx covers 32
consecutive byte addresses; the byte at word address (xx*32 + k) sits at bits
[k*8 +: 8].  Parity (INITP / the 9th bit) is left 0.

Emits one `include fragment per lane: <outdir>/progmem_init_lane{0..3}.svh, each
to be `included inside its RAMB16_S9_S9 #( ... ) instance in progmem_bram.v.

Usage:  python3 bin2init.py firmware.bin [outdir=.]
"""
import struct, sys, os

DEPTH = 2048

binfile = sys.argv[1]
outdir  = sys.argv[2] if len(sys.argv) > 2 else "."

data = open(binfile, "rb").read()
data += b"\x00" * ((-len(data)) % 4)            # pad to 32-bit boundary
words = [struct.unpack("<I", data[i:i+4])[0] for i in range(0, len(data), 4)]

if len(words) > DEPTH:
    sys.exit("bin2init.py: firmware %d words > %d (2048-word progmem) — "
             "shrink firmware" % (len(words), DEPTH))
words += [0] * (DEPTH - len(words))             # zero-fill the rest

def lane_inits(lane):
    """Return list of (xx, 256-bit val) for byte-lane `lane`."""
    out = []
    for xx in range(64):                        # INIT_00 .. INIT_3F (2048/32)
        val = 0
        for k in range(32):                     # 32 bytes per 256-bit INIT
            byte = (words[xx * 32 + k] >> (lane * 8)) & 0xFF
            val |= byte << (k * 8)
        out.append((xx, val))
    return out

for lane in range(4):
    path = os.path.join(outdir, "progmem_init_lane%d.svh" % lane)
    with open(path, "w") as f:
        f.write("// generated by bin2init.py from %s — byte lane %d of 4\n"
                % (os.path.basename(binfile), lane))
        f.write(",\n".join(".INIT_%02X(256'h%064x)" % (xx, v)
                           for xx, v in lane_inits(lane)) + "\n")

# ---- round-trip self-check: reconstruct words from the 4 lanes, compare ----
recon = [0] * DEPTH
for lane in range(4):
    for xx, v in lane_inits(lane):
        for k in range(32):
            recon[xx * 32 + k] |= ((v >> (k * 8)) & 0xFF) << (lane * 8)
if recon != words:
    sys.exit("bin2init.py: ROUND-TRIP MISMATCH — byte-lane packing is wrong")
sys.stderr.write("bin2init.py: %d words -> 4 lane INITs in %s (round-trip OK, %d non-zero)\n"
                 % (len(words), outdir, sum(1 for w in words if w)))
