/* fw_engine.c — PicoSoC + real-engine console (lean build).
 * UART is the only SoC-visible channel in this engine top (LEDs belong to the
 * engine; the eth LSU bus + ddr_wr upload path are tied off in this lean build).
 * It serves an interactive single-key menu that reads the engine regmap over the
 * Avalon master bridge (iomem 0x10) + the status snapshot (iomem 0x40), so every
 * command also proves the SoC<->engine register path works.  No globals. */
#include <stdint.h>

#define reg_uart_clkdiv (*(volatile uint32_t *)0x02000004)
#define reg_uart_data   (*(volatile uint32_t *)0x02000008)
#define UART_DIV 1085                 /* 125 MHz eth_clk / 115200 */

#define REG(n) (*(volatile uint32_t *)(0x10000000u + ((uint32_t)(n) << 2)))
#define HB     (*(volatile uint32_t *)0x40000000u)   /* engine status snapshot */

/* Engine regmap addresses (R_*) — single source of truth shared with the RTL
 * (regmap_gen.svh); both auto-generated by host/gen_regmap.py.  Never hardcode
 * a regmap address here — add it to the generator and use the symbol. */
#include "regmap_gen.h"

/* Bridge iomem DDR3 write window (NOT the engine regmap): a 32-bit data port
 * fills a 512-bit beat one word at a time; the addr port sets the 64-byte byte
 * address (auto-advances per beat).  The 16th DDR_DATA store blocks the CPU
 * until the AXI write completes (back-pressure), so just stream 16 words/beat. */
#define DDR_DATA (*(volatile uint32_t *)0x30000000u)
#define DDR_ADDR (*(volatile uint32_t *)0x31000000u)
#define DDR_TEST_BEATS 16u                /* test pattern size (16*64 = 1 KiB) */
/* word(i) = i * MUL with an ODD multiplier, so the 16 words of a 64-byte beat
 * don't XOR-cancel (16 *consecutive* ints fold to 0 — a useless test).  This
 * makes each beat's fold non-zero so the rolling scan-CRC actually moves. */
#define DDR_TEST_MUL   0x9E3779B1u

/* UART_TXDELAY (compile-time, default OFF): busy-wait one+ byte-time after every
 * UART byte so multi-char output survives even if the CPU isn't stalled by the
 * UART back-pressure.  Used to confirm the bridge catch-all overrun on the old
 * (pre-fix) bitstream WITHOUT a rebuild.  >1 byte-time @115200/125MHz ~= 10850
 * eth_clk cycles; 4000 loop iters at picorv32's ~20 cyc/iter clears it amply. */
#ifdef UART_TXDELAY
#define UART_TXWAIT do { volatile int _d; for (_d = 0; _d < 4000; _d++); } while (0)
#else
#define UART_TXWAIT do { } while (0)
#endif
static void putc_(char c) {
    if (c == '\n') { reg_uart_data = '\r'; UART_TXWAIT; }
    reg_uart_data = c; UART_TXWAIT;
}
static void print_(const char *s) { while (*s) putc_(*s++); }
static void hex_(uint32_t v, int nyb) {
    for (int i = nyb - 1; i >= 0; i--) putc_("0123456789abcdef"[(v >> (4 * i)) & 15]);
}

static void menu(void) {
    print_("\nfw_engine " __DATE__ " " __TIME__ "\n");
    print_("v ver  c crc  s status  w ddrwr  k scancrc  r restart  ? menu\n");
}

static void cmd_version(void) {
    print_("BUILD_VERSION="); hex_(REG(R_BUILDVER), 8); putc_('\n');
}

static void cmd_crc(void) {
    print_("weight CRC=");  hex_(REG(R_CRC), 8);
    print_("  has_run=");   hex_(REG(R_HAS_RUN) & 1, 1); putc_('\n');
}

static void cmd_status(void) {
    uint32_t hb = HB;
    print_("state=");      hex_(hb        & 0xFF, 2);
    print_(" last_tok=");  hex_((hb >>  8) & 0xFF, 2);
    print_(" out_len=");   hex_((hb >> 16) & 0xFF, 2);
    print_(" flags=");     hex_((hb >> 24) & 0xFF, 2);  /* [0]error [1]done */
    putc_('\n');
    uint32_t ml = REG(R_ML_STATE);
    print_("ml_state=");   hex_(ml & 7, 1);
    print_(" layer=");     hex_((ml >> 3) & 0x1F, 2);
    print_(" calib=");     hex_(REG(R_DBG_CALIB) & 1, 1);
    print_(" layer_done=");hex_(REG(R_LAYER_DONE) & 3, 1);
    putc_('\n');
}

static void cmd_restart(void) {
    REG(R_RESTART) = 1;
    print_("restart pulsed (0x1F1)\n");
}

/* Roll the same hash the idle scanner computes in HW (idle_scan_crc.sv):
 * crc=0xFFFFFFFF; per 64-byte beat fold = XOR of its 16 words; crc=rotl(crc,1)^fold. */
static uint32_t scan_ref(uint32_t nbeats) {
    uint32_t crc = 0xFFFFFFFFu, gi = 0;
    for (uint32_t b = 0; b < nbeats; b++) {
        uint32_t fold = 0;
        for (uint32_t w = 0; w < 16; w++) { fold ^= gi * DDR_TEST_MUL; gi++; }
        crc = (crc << 1) | (crc >> 31);
        crc ^= fold;
    }
    return crc;
}

/* 'w': stream a known word(i)=i*MUL pattern into DDR3 via the bridge window. */
static void cmd_ddrwrite(void) {
    print_("ddr write "); hex_(DDR_TEST_BEATS, 2); print_(" beats @0...");
    uint32_t gi = 0;
    DDR_ADDR = 0;                                  /* start byte addr (auto-advances) */
    for (uint32_t b = 0; b < DDR_TEST_BEATS; b++)
        for (uint32_t w = 0; w < 16; w++) DDR_DATA = gi++ * DDR_TEST_MUL;
    print_("done\n");
}

/* 'k': trigger the idle scan-CRC over the written region, compare to the C ref. */
static void cmd_scan(void) {
    print_("scan-CRC ");
    REG(R_SCAN_BASE) = 0;
    REG(R_SCAN_LEN)  = DDR_TEST_BEATS;
    REG(R_SCAN_TRIG) = 1;
    uint32_t to = 4000000u;
    while (!(REG(R_SCAN_STAT) & 2) && --to) { }    /* bit1 = done */
    if (!to) { print_("TIMEOUT (scanner not responding)\n"); return; }
    uint32_t hw  = REG(R_SCAN_CRC);
    uint32_t ref = scan_ref(DDR_TEST_BEATS);
    print_("hw="); hex_(hw, 8); print_(" ref="); hex_(ref, 8);
    print_(hw == ref ? "  PASS\n" : "  FAIL\n");
}

void main(void)
{
    reg_uart_clkdiv = UART_DIV;
    print_("\n=== PicoSoC engine console ===\n");
    cmd_version();
    menu();
    print_("> ");
    for (;;) {
        int32_t c = reg_uart_data;
        if (c == -1) continue;
        char ch = (char)c;
        if (ch == '\r' || ch == '\n') { print_("> "); continue; }
        putc_(ch); putc_('\n');
        switch (ch) {
            case 'v': cmd_version(); break;
            case 'c': cmd_crc();     break;
            case 's': cmd_status();  break;
            case 'w': cmd_ddrwrite();break;
            case 'k': cmd_scan();    break;
            case 'r': cmd_restart(); break;
            case '?':
            case 'h': menu();        break;
            default:  print_("? press ? for menu\n");
        }
        print_("> ");
    }
}
