/* fw_engine.c — PicoSoC + real-engine console + weight uploader.
 * Channels: UART menu (debug) on 0x02; engine regmap via the Avalon bridge
 * (iomem 0x10) + status snapshot (0x40); DDR3 write window (0x30/0x31); idle
 * scan-CRC (regmap 0x080-0x084); and the ethernet MAC over the LSU window (0x20).
 * Stage 2: the firmware parses bfp_client's UDP frames (FT_DDR_WRITE -> DDR3) in
 * the main loop, replacing the old microgpt_eth_ctrl HW FSM. */
#include <stdint.h>

#define reg_uart_clkdiv (*(volatile uint32_t *)0x02000004)
#define reg_uart_data   (*(volatile uint32_t *)0x02000008)
#define UART_DIV 1085                 /* 125 MHz eth_clk / 115200 */

#define REG(n) (*(volatile uint32_t *)(0x10000000u + ((uint32_t)(n) << 2)))
#define HB     (*(volatile uint32_t *)0x40000000u)   /* engine status snapshot */

/* Engine regmap addresses (R_*) — single source of truth shared with the RTL
 * (regmap_gen.svh); both auto-generated by host/gen_regmap.py.  Never hardcode
 * a regmap address here — add it to the generator and use the symbol. */
#include "regmap_gen.h"

/* Bridge iomem DDR3 write window (NOT the engine regmap): a 32-bit data port
 * fills a 512-bit beat one word at a time; the addr port sets the 64-byte byte
 * address (auto-advances per beat).  The 16th DDR_DATA store blocks the CPU
 * until the AXI write completes (back-pressure), so just stream 16 words/beat. */
#define DDR_DATA (*(volatile uint32_t *)0x30000000u)
#define DDR_ADDR (*(volatile uint32_t *)0x31000000u)
#define DDR_TEST_BEATS 16u                /* test pattern size (16*64 = 1 KiB) */
/* word(i) = i * MUL with an ODD multiplier, so the 16 words of a 64-byte beat
 * don't XOR-cancel (16 *consecutive* ints fold to 0 — a useless test).  This
 * makes each beat's fold non-zero so the rolling scan-CRC actually moves. */
#define DDR_TEST_MUL   0x9E3779B1u

/* Ethernet MAC over the LSU window (iomem 0x20 + lsu_byte_addr).  Each 32-bit
 * access maps to a 64-bit LSU word (low half = +0, high half = +4).  bfp_client
 * sends raw UDP frames; the payload starts at frame byte 42 (= RX 64-bit word 5,
 * byte 2).  This build parses FT_DDR_WRITE only (weight upload). */
#define ETH(off)  (*(volatile uint32_t *)(0x20000000u + (off)))
#define ETH_MACLO 0x0800u
#define ETH_MACHI 0x0808u   /* [20]irq_en [19]promiscuous ... [15:0]mac[47:32] */
#define ETH_RXEN  0x0828u
#define ETH_RSR   0x0830u   /* rd: [15]=ready,[4:0]=buf ; wr: (buf+1) frees */
#define ETH_TPLR  0x0810u   /* write {tbuf<<11 | byte_len} -> send */
#define ETH_RX(b, w) (0x10000u + ((uint32_t)(b) << 11) + ((uint32_t)(w) << 3))
#define ETH_TX(t, w) (0x1000u  + ((uint32_t)(t) << 11) + ((uint32_t)(w) << 3))
#define MAC_LO 0x004D4731u  /* old eth_ctrl MAC (promiscuous below, so it's moot) */
#define MAC_HI 0x00000200u
#define FT_DDR_WRITE 0x0Au  /* UDP payload byte 0 = frame byte 42 */
#define FT_REG_WRITE 0x01u
#define FT_REG_READ  0x02u
#define FT_REG_RSP   0x03u
#define FT_ACK       0x06u
#define FPGA_UDP_PORT 19783u  /* 0x4D47 "MG" — only frames to this port are handled */
#define ETYPE_ARP 0x0806u
#define ETYPE_IP  0x0800u
#define IPPROTO_ICMP 1u
#define IPPROTO_UDP  17u
/* FPGA static IP — host pings/targets this; ARP makes it reachable. */
#define FIP0 192u
#define FIP1 168u
#define FIP2 1u
#define FIP3 42u

/* UART_TXDELAY (compile-time, default OFF): busy-wait one+ byte-time after every
 * UART byte so multi-char output survives even if the CPU isn't stalled by the
 * UART back-pressure.  Used to confirm the bridge catch-all overrun on the old
 * (pre-fix) bitstream WITHOUT a rebuild.  >1 byte-time @115200/125MHz ~= 10850
 * eth_clk cycles; 4000 loop iters at picorv32's ~20 cyc/iter clears it amply. */
#ifdef UART_TXDELAY
#define UART_TXWAIT do { volatile int _d; for (_d = 0; _d < 4000; _d++); } while (0)
#else
#define UART_TXWAIT do { } while (0)
#endif
static void putc_(char c) {
    if (c == '\n') { reg_uart_data = '\r'; UART_TXWAIT; }
    reg_uart_data = c; UART_TXWAIT;
}
static void print_(const char *s) { while (*s) putc_(*s++); }
static void hex_(uint32_t v, int nyb) {
    for (int i = nyb - 1; i >= 0; i--) putc_("0123456789abcdef"[(v >> (4 * i)) & 15]);
}

static void menu(void) {
    print_("\nfw_engine " __DATE__ " " __TIME__ "\n");
    print_("v ver  c crc  s status  w ddrwr  k scancrc  e eth  r restart  ? menu\n");
}

static void cmd_version(void) {
    print_("BUILD_VERSION="); hex_(REG(R_BUILDVER), 8); putc_('\n');
}

static void cmd_crc(void) {
    print_("weight CRC=");  hex_(REG(R_CRC), 8);
    print_("  has_run=");   hex_(REG(R_HAS_RUN) & 1, 1); putc_('\n');
}

static void cmd_status(void) {
    uint32_t hb = HB;
    print_("state=");      hex_(hb        & 0xFF, 2);
    print_(" last_tok=");  hex_((hb >>  8) & 0xFF, 2);
    print_(" out_len=");   hex_((hb >> 16) & 0xFF, 2);
    print_(" flags=");     hex_((hb >> 24) & 0xFF, 2);  /* [0]error [1]done */
    putc_('\n');
    uint32_t ml = REG(R_ML_STATE);
    print_("ml_state=");   hex_(ml & 7, 1);
    print_(" layer=");     hex_((ml >> 3) & 0x1F, 2);
    print_(" calib=");     hex_(REG(R_DBG_CALIB) & 1, 1);
    print_(" layer_done=");hex_(REG(R_LAYER_DONE) & 3, 1);
    putc_('\n');
}

static void cmd_restart(void) {
    REG(R_RESTART) = 1;
    print_("restart pulsed (0x1F1)\n");
}

/* Roll the same hash the idle scanner computes in HW (idle_scan_crc.sv):
 * crc=0xFFFFFFFF; per 64-byte beat fold = XOR of its 16 words; crc=rotl(crc,1)^fold. */
static uint32_t scan_ref(uint32_t nbeats) {
    uint32_t crc = 0xFFFFFFFFu, gi = 0;
    for (uint32_t b = 0; b < nbeats; b++) {
        uint32_t fold = 0;
        for (uint32_t w = 0; w < 16; w++) { fold ^= gi * DDR_TEST_MUL; gi++; }
        crc = (crc << 1) | (crc >> 31);
        crc ^= fold;
    }
    return crc;
}

/* 'w': stream a known word(i)=i*MUL pattern into DDR3 via the bridge window. */
static void cmd_ddrwrite(void) {
    print_("ddr write "); hex_(DDR_TEST_BEATS, 2); print_(" beats @0...");
    uint32_t gi = 0;
    DDR_ADDR = 0;                                  /* start byte addr (auto-advances) */
    for (uint32_t b = 0; b < DDR_TEST_BEATS; b++)
        for (uint32_t w = 0; w < 16; w++) DDR_DATA = gi++ * DDR_TEST_MUL;
    print_("done\n");
}

/* 'k': trigger the idle scan-CRC over the written region, compare to the C ref. */
static void cmd_scan(void) {
    print_("scan-CRC ");
    REG(R_SCAN_BASE) = 0;
    REG(R_SCAN_LEN)  = DDR_TEST_BEATS;
    REG(R_SCAN_TRIG) = 1;
    uint32_t to = 4000000u;
    while (!(REG(R_SCAN_STAT) & 2) && --to) { }    /* bit1 = done */
    if (!to) { print_("TIMEOUT (scanner not responding)\n"); return; }
    uint32_t hw  = REG(R_SCAN_CRC);
    uint32_t ref = scan_ref(DDR_TEST_BEATS);
    print_("hw="); hex_(hw, 8); print_(" ref="); hex_(ref, 8);
    print_(hw == ref ? "  PASS\n" : "  FAIL\n");
}

static uint8_t  ethf[256];        /* reply-frame scratch (headers + payload) */
static uint32_t eth_beats = 0;    /* DDR3 beats written from eth frames */
static uint32_t eth_acks  = 0;    /* replies sent (ACK/REG_RSP/ARP/ICMP) */
static const uint8_t FMAC[6] = {0x02,0x00,0x00,0x4D,0x47,0x31};  /* FPGA MAC */
static const uint8_t FIP[4]  = {FIP0, FIP1, FIP2, FIP3};         /* FPGA IP  */

static void eth_init(void) {
    ETH(ETH_MACLO) = MAC_LO;
    ETH(ETH_MACHI) = MAC_HI | (1u << 22);   /* enable; no promiscuous — ARP makes us reachable */
    ETH(ETH_RXEN)  = 31;
}

/* Copy n (mult of 4) bytes between a byte array and the RX/TX LSU window.  Each
 * 64-bit LSU word is two 32-bit halves: ETH_RX/TX(b,w) = low half (bytes w*8..+3),
 * +4 = high half.  i>>3 = word index, i&4 = the half offset. */
static void eth_rx_bytes(uint32_t b, uint8_t *d, uint32_t n) {
    for (uint32_t i = 0; i < n; i += 4) {
        uint32_t v = ETH(ETH_RX(b, i >> 3) + (i & 4));
        d[i] = v; d[i+1] = v >> 8; d[i+2] = v >> 16; d[i+3] = v >> 24;
    }
}
static void eth_tx_bytes(const uint8_t *s, uint32_t n) {   /* always TX buffer 0 */
    for (uint32_t i = 0; i < n; i += 4)
        ETH(ETH_TX(0, i >> 3) + (i & 4)) =
            s[i] | (s[i+1] << 8) | (s[i+2] << 16) | (s[i+3] << 24);
}
static void bswap(uint8_t *a, uint8_t *c, int n) { while (n--) { uint8_t t = *a; *a++ = *c; *c++ = t; } }
static uint8_t rxb(uint32_t b, uint32_t off) {     /* one frame byte from the RX buffer */
    return ETH(ETH_RX(b, off >> 3) + (off & 4)) >> ((off & 3) * 8);
}
static uint16_t cksum16(const uint8_t *p, uint32_t n) {  /* internet checksum (IP/ICMP) */
    uint32_t s = 0;
    for (uint32_t i = 0; i + 1 < n; i += 2) s += (p[i] << 8) | p[i+1];
    if (n & 1) s += p[n-1] << 8;
    while (s >> 16) s = (s & 0xFFFF) + (s >> 16);
    return ~s;
}

/* Reg-read value: serve the counters bfp_client polls for flow control from our
 * own state (so it sees real upload progress); else read the engine regmap. */
static uint32_t eth_regval(uint16_t a) {
    switch (a) {
        case 0x18: return 0;                               /* eth ring: empty   */
        case 0x19: case 0x1A: case 0x1B: return eth_beats; /* rx / done / ack    */
        case 0x1C: return eth_acks;                        /* FT_ACK tx count    */
        default:   return REG(a);
    }
}

/* Reply by reflecting the request headers in ethf[0..41] (swap MAC/IP/port, fix
 * lengths + IP checksum); payload pre-filled at ethf[42..].  Sent from TX buf 0. */
static void eth_reply(uint32_t plen) {
    bswap(&ethf[0],  &ethf[6],  6);   /* eth dst<->src MAC  */
    bswap(&ethf[26], &ethf[30], 4);   /* IP  src<->dst      */
    bswap(&ethf[34], &ethf[36], 2);   /* UDP src<->dst port */
    uint32_t iplen = 28 + plen, ulen = 8 + plen;
    ethf[16] = iplen >> 8; ethf[17] = iplen;   /* IP total length (BE) */
    ethf[38] = ulen >> 8;  ethf[39] = ulen;    /* UDP length (BE)      */
    ethf[40] = 0; ethf[41] = 0;                /* UDP checksum = 0     */
    ethf[24] = 0; ethf[25] = 0;
    uint16_t ck = cksum16(&ethf[14], 20);      /* IP checksum over hdr */
    ethf[24] = ck >> 8; ethf[25] = ck;
    uint32_t flen = 42 + plen;
    while (flen < 60) ethf[flen++] = 0;        /* pad to eth min frame */
    eth_tx_bytes(ethf, (flen + 3) & ~3u);
    ETH(ETH_TPLR) = flen;                       /* tbuf 0, byte_len = flen */
    eth_acks++;
}

/* ARP: reply to a who-has for our IP with "is-at FMAC". */
static void eth_arp(uint32_t b) {
    eth_rx_bytes(b, ethf, 48);                     /* eth(14)+ARP(28)=42, read 48 */
    if (ethf[20] != 0 || ethf[21] != 1) return;    /* OPER must be request (1) */
    if (ethf[38]!=FIP[0] || ethf[39]!=FIP[1] || ethf[40]!=FIP[2] || ethf[41]!=FIP[3]) return; /* TPA != us */
    for (int i = 0; i < 6; i++) { ethf[i] = ethf[22+i]; ethf[32+i] = ethf[22+i]; }   /* dst & THA = requester MAC */
    for (int i = 0; i < 4; i++)   ethf[38+i] = ethf[28+i];                           /* TPA = requester IP */
    for (int i = 0; i < 6; i++) { ethf[6+i] = FMAC[i]; ethf[22+i] = FMAC[i]; }       /* src & SHA = us */
    for (int i = 0; i < 4; i++)   ethf[28+i] = FIP[i];                               /* SPA = us */
    ethf[20] = 0; ethf[21] = 2;                    /* OPER = reply (2) */
    uint32_t flen = 42;
    while (flen < 60) ethf[flen++] = 0;
    eth_tx_bytes(ethf, (flen + 3) & ~3u);
    ETH(ETH_TPLR) = flen;
    eth_acks++;
}

/* ICMP: reply to an echo request (ping) with an echo reply. */
static void eth_icmp(uint32_t b) {
    uint32_t iptot = (rxb(b, 16) << 8) | rxb(b, 17);   /* IP total length */
    uint32_t flen  = 14 + iptot;
    if (flen > sizeof(ethf)) return;                   /* oversize ping — ignore */
    eth_rx_bytes(b, ethf, (flen + 3) & ~3u);
    if (ethf[34] != 8) return;                         /* ICMP type 8 = echo request */
    bswap(&ethf[0], &ethf[6], 6);                      /* swap eth MAC */
    bswap(&ethf[26], &ethf[30], 4);                    /* swap IP src/dst */
    ethf[34] = 0;                                       /* echo reply */
    ethf[36] = 0; ethf[37] = 0;
    uint16_t ic = cksum16(&ethf[34], iptot - 20);      /* ICMP checksum over message */
    ethf[36] = ic >> 8; ethf[37] = ic;
    ethf[24] = 0; ethf[25] = 0;
    uint16_t ip = cksum16(&ethf[14], 20);              /* IP header checksum */
    ethf[24] = ip >> 8; ethf[25] = ip;
    while (flen < 60) ethf[flen++] = 0;
    eth_tx_bytes(ethf, (flen + 3) & ~3u);
    ETH(ETH_TPLR) = flen;
    eth_acks++;
}

/* Service one RX frame: ARP who-has us -> reply; ICMP echo to us -> reply; UDP to
 * our IP:port -> the bfp_client FT_* protocol (DDR upload / regmap, with replies). */
static void eth_handle(void) {
    uint32_t rsr = ETH(ETH_RSR);
    if (!(rsr & (1u << 15))) return;
    uint32_t b = rsr & 0x1f;
    uint16_t etype = (rxb(b, 12) << 8) | rxb(b, 13);
    if (etype == ETYPE_ARP) {
        eth_arp(b);
    } else if (etype == ETYPE_IP &&
               rxb(b,30)==FIP[0] && rxb(b,31)==FIP[1] && rxb(b,32)==FIP[2] && rxb(b,33)==FIP[3]) {
        uint8_t proto = rxb(b, 23);
        if (proto == IPPROTO_ICMP) {
            eth_icmp(b);
        } else if (proto == IPPROTO_UDP && ((rxb(b,36) << 8) | rxb(b,37)) == FPGA_UDP_PORT) {
            uint32_t w5  = ETH(ETH_RX(b, 5));
            uint8_t  ft  = (w5 >> 16) & 0xFF;             /* byte 42 = frame type */
            uint8_t  seq = (w5 >> 24) & 0xFF;             /* byte 43 = seq */
            if (ft == FT_DDR_WRITE) {
                DDR_ADDR = ETH(ETH_RX(b, 5) + 4) & 0x3FFFFFFFu;   /* bytes 44-47 */
                for (uint32_t c = 0; c < 8; c++) {                /* RX words 6..13 */
                    DDR_DATA = ETH(ETH_RX(b, 6 + c));
                    DDR_DATA = ETH(ETH_RX(b, 6 + c) + 4);
                }
                eth_beats++;
                eth_rx_bytes(b, ethf, 48);
                ethf[42] = FT_ACK; ethf[43] = seq;
                eth_reply(2);
            } else if (ft == FT_REG_WRITE) {
                uint8_t n = ETH(ETH_RX(b, 5) + 4) & 0xFF;
                for (uint32_t i = 0; i < n; i++) {
                    uint32_t lo = ETH(ETH_RX(b, 6 + i));
                    REG((lo >> 16) & 0xFFFF) = ETH(ETH_RX(b, 6 + i) + 4);
                }
                eth_rx_bytes(b, ethf, 48);
                ethf[42] = FT_ACK; ethf[43] = seq;
                eth_reply(2);
            } else if (ft == FT_REG_READ) {
                uint32_t w5h    = ETH(ETH_RX(b, 5) + 4);
                uint16_t addr   = w5h & 0xFFFF;
                uint8_t  nwords = (w5h >> 16) & 0xFF;
                if (nwords > 19) nwords = 19;
                eth_rx_bytes(b, ethf, 48);
                ethf[42] = FT_REG_RSP; ethf[43] = seq;
                ethf[44] = addr; ethf[45] = addr >> 8;
                ethf[46] = nwords; ethf[47] = 0; ethf[48] = 0; ethf[49] = 0;
                for (uint32_t i = 0; i < nwords; i++) {
                    uint32_t v = eth_regval(addr + i);
                    ethf[50+i*4] = v; ethf[51+i*4] = v>>8; ethf[52+i*4] = v>>16; ethf[53+i*4] = v>>24;
                }
                eth_reply(8 + nwords * 4);
            }
        }
    }
    ETH(ETH_RSR) = (b + 1) & 0x1f;                    /* free the buffer */
}

static void cmd_eth(void) {
    print_("eth beats="); hex_(eth_beats, 8);
    print_(" acks=");      hex_(eth_acks, 8); putc_('\n');
}

void main(void)
{
    reg_uart_clkdiv = UART_DIV;
    print_("\n=== PicoSoC engine console ===\n");
    cmd_version();
    eth_init();
    menu();
    print_("> ");
    for (;;) {
        eth_handle();                 /* service one eth RX frame (weight upload) */
        int32_t c = reg_uart_data;
        if (c == -1) continue;
        char ch = (char)c;
        if (ch == '\r' || ch == '\n') { print_("> "); continue; }
        putc_(ch); putc_('\n');
        switch (ch) {
            case 'v': cmd_version(); break;
            case 'c': cmd_crc();     break;
            case 's': cmd_status();  break;
            case 'w': cmd_ddrwrite();break;
            case 'k': cmd_scan();    break;
            case 'e': cmd_eth();     break;
            case 'r': cmd_restart(); break;
            case '?':
            case 'h': menu();        break;
            default:  print_("? press ? for menu\n");
        }
        print_("> ");
    }
}
