/* fw_engine.c — PicoSoC + real-engine console + weight uploader.
 * Channels: UART menu (debug) on 0x02; engine regmap via the Avalon bridge
 * (iomem 0x10) + status snapshot (0x40); DDR3 write window (0x30/0x31); idle
 * scan-CRC (regmap 0x080-0x084); and the ethernet MAC over the LSU window (0x20).
 * Stage 2: the firmware parses bfp_client's UDP frames (FT_DDR_WRITE -> DDR3) in
 * the main loop, replacing the old microgpt_eth_ctrl HW FSM. */
#include <stdint.h>

#define reg_uart_clkdiv (*(volatile uint32_t *)0x02000004)
#define reg_uart_data   (*(volatile uint32_t *)0x02000008)
#define UART_DIV 1085                 /* 125 MHz eth_clk / 115200 */

#define REG(n) (*(volatile uint32_t *)(0x10000000u + ((uint32_t)(n) << 2)))
#define HB     (*(volatile uint32_t *)0x40000000u)   /* engine status snapshot */

/* Engine regmap addresses (R_*) — single source of truth shared with the RTL
 * (regmap_gen.svh); both auto-generated by host/gen_regmap.py.  Never hardcode
 * a regmap address here — add it to the generator and use the symbol. */
#include "regmap_gen.h"

/* Bridge iomem DDR3 write window (NOT the engine regmap): a 32-bit data port
 * fills a 512-bit beat one word at a time; the addr port sets the 64-byte byte
 * address (auto-advances per beat).  The 16th DDR_DATA store blocks the CPU
 * until the AXI write completes (back-pressure), so just stream 16 words/beat. */
#define DDR_DATA (*(volatile uint32_t *)0x30000000u)
#define DDR_ADDR (*(volatile uint32_t *)0x31000000u)
#define DDR_TEST_BEATS 16u                /* test pattern size (16*64 = 1 KiB) */
/* word(i) = i * MUL with an ODD multiplier, so the 16 words of a 64-byte beat
 * don't XOR-cancel (16 *consecutive* ints fold to 0 — a useless test).  This
 * makes each beat's fold non-zero so the rolling scan-CRC actually moves. */
#define DDR_TEST_MUL   0x9E3779B1u

/* Ethernet MAC over the LSU window (iomem 0x20 + lsu_byte_addr).  Each 32-bit
 * access maps to a 64-bit LSU word (low half = +0, high half = +4).  bfp_client
 * sends raw UDP frames; the payload starts at frame byte 42 (= RX 64-bit word 5,
 * byte 2).  This build parses FT_DDR_WRITE only (weight upload). */
#define ETH(off)  (*(volatile uint32_t *)(0x20000000u + (off)))
#define ETH_MACLO 0x0800u
#define ETH_MACHI 0x0808u   /* [20]irq_en [19]promiscuous ... [15:0]mac[47:32] */
#define ETH_RXEN  0x0828u
#define ETH_RSR   0x0830u   /* rd: [15]=ready,[4:0]=buf ; wr: (buf+1) frees */
#define ETH_RX(b, w) (0x10000u + ((uint32_t)(b) << 11) + ((uint32_t)(w) << 3))
#define MAC_LO 0x004D4731u  /* old eth_ctrl MAC (promiscuous below, so it's moot) */
#define MAC_HI 0x00000200u
#define FT_DDR_WRITE 0x0Au  /* UDP payload byte 0 = frame byte 42 */

/* UART_TXDELAY (compile-time, default OFF): busy-wait one+ byte-time after every
 * UART byte so multi-char output survives even if the CPU isn't stalled by the
 * UART back-pressure.  Used to confirm the bridge catch-all overrun on the old
 * (pre-fix) bitstream WITHOUT a rebuild.  >1 byte-time @115200/125MHz ~= 10850
 * eth_clk cycles; 4000 loop iters at picorv32's ~20 cyc/iter clears it amply. */
#ifdef UART_TXDELAY
#define UART_TXWAIT do { volatile int _d; for (_d = 0; _d < 4000; _d++); } while (0)
#else
#define UART_TXWAIT do { } while (0)
#endif
static void putc_(char c) {
    if (c == '\n') { reg_uart_data = '\r'; UART_TXWAIT; }
    reg_uart_data = c; UART_TXWAIT;
}
static void print_(const char *s) { while (*s) putc_(*s++); }
static void hex_(uint32_t v, int nyb) {
    for (int i = nyb - 1; i >= 0; i--) putc_("0123456789abcdef"[(v >> (4 * i)) & 15]);
}

static void menu(void) {
    print_("\nfw_engine " __DATE__ " " __TIME__ "\n");
    print_("v ver  c crc  s status  w ddrwr  k scancrc  e eth  r restart  ? menu\n");
}

static void cmd_version(void) {
    print_("BUILD_VERSION="); hex_(REG(R_BUILDVER), 8); putc_('\n');
}

static void cmd_crc(void) {
    print_("weight CRC=");  hex_(REG(R_CRC), 8);
    print_("  has_run=");   hex_(REG(R_HAS_RUN) & 1, 1); putc_('\n');
}

static void cmd_status(void) {
    uint32_t hb = HB;
    print_("state=");      hex_(hb        & 0xFF, 2);
    print_(" last_tok=");  hex_((hb >>  8) & 0xFF, 2);
    print_(" out_len=");   hex_((hb >> 16) & 0xFF, 2);
    print_(" flags=");     hex_((hb >> 24) & 0xFF, 2);  /* [0]error [1]done */
    putc_('\n');
    uint32_t ml = REG(R_ML_STATE);
    print_("ml_state=");   hex_(ml & 7, 1);
    print_(" layer=");     hex_((ml >> 3) & 0x1F, 2);
    print_(" calib=");     hex_(REG(R_DBG_CALIB) & 1, 1);
    print_(" layer_done=");hex_(REG(R_LAYER_DONE) & 3, 1);
    putc_('\n');
}

static void cmd_restart(void) {
    REG(R_RESTART) = 1;
    print_("restart pulsed (0x1F1)\n");
}

/* Roll the same hash the idle scanner computes in HW (idle_scan_crc.sv):
 * crc=0xFFFFFFFF; per 64-byte beat fold = XOR of its 16 words; crc=rotl(crc,1)^fold. */
static uint32_t scan_ref(uint32_t nbeats) {
    uint32_t crc = 0xFFFFFFFFu, gi = 0;
    for (uint32_t b = 0; b < nbeats; b++) {
        uint32_t fold = 0;
        for (uint32_t w = 0; w < 16; w++) { fold ^= gi * DDR_TEST_MUL; gi++; }
        crc = (crc << 1) | (crc >> 31);
        crc ^= fold;
    }
    return crc;
}

/* 'w': stream a known word(i)=i*MUL pattern into DDR3 via the bridge window. */
static void cmd_ddrwrite(void) {
    print_("ddr write "); hex_(DDR_TEST_BEATS, 2); print_(" beats @0...");
    uint32_t gi = 0;
    DDR_ADDR = 0;                                  /* start byte addr (auto-advances) */
    for (uint32_t b = 0; b < DDR_TEST_BEATS; b++)
        for (uint32_t w = 0; w < 16; w++) DDR_DATA = gi++ * DDR_TEST_MUL;
    print_("done\n");
}

/* 'k': trigger the idle scan-CRC over the written region, compare to the C ref. */
static void cmd_scan(void) {
    print_("scan-CRC ");
    REG(R_SCAN_BASE) = 0;
    REG(R_SCAN_LEN)  = DDR_TEST_BEATS;
    REG(R_SCAN_TRIG) = 1;
    uint32_t to = 4000000u;
    while (!(REG(R_SCAN_STAT) & 2) && --to) { }    /* bit1 = done */
    if (!to) { print_("TIMEOUT (scanner not responding)\n"); return; }
    uint32_t hw  = REG(R_SCAN_CRC);
    uint32_t ref = scan_ref(DDR_TEST_BEATS);
    print_("hw="); hex_(hw, 8); print_(" ref="); hex_(ref, 8);
    print_(hw == ref ? "  PASS\n" : "  FAIL\n");
}

static uint32_t eth_beats = 0;   /* DDR3 beats written from eth frames (debug) */

static void eth_init(void) {
    ETH(ETH_MACLO) = MAC_LO;
    ETH(ETH_MACHI) = MAC_HI | (1u << 22) | (1u << 19);  /* enable + promiscuous */
    ETH(ETH_RXEN)  = 31;
}

/* Service one RX frame.  FT_DDR_WRITE -> stream the 64-byte payload into DDR3 at
 * the frame's byte address.  Byte layout matches the old HW FSM: the 512-bit beat
 * = RX 64-bit words 6..13, so DDR window word 2c/2c+1 = lo/hi of RX word 6+c. */
static void eth_handle(void) {
    uint32_t rsr = ETH(ETH_RSR);
    if (!(rsr & (1u << 15))) return;                  /* no frame ready */
    uint32_t b = rsr & 0x1f;
    uint32_t w5 = ETH(ETH_RX(b, 5));                  /* frame bytes 40-43 */
    if (((w5 >> 16) & 0xFF) == FT_DDR_WRITE) {        /* byte 42 = frame type */
        DDR_ADDR = ETH(ETH_RX(b, 5) + 4) & 0x3FFFFFFFu;   /* bytes 44-47 = byte addr */
        for (uint32_t c = 0; c < 8; c++) {            /* RX words 6..13 = 64 data bytes */
            DDR_DATA = ETH(ETH_RX(b, 6 + c));             /* lo 32 */
            DDR_DATA = ETH(ETH_RX(b, 6 + c) + 4);         /* hi 32 */
        }
        eth_beats++;
    }
    ETH(ETH_RSR) = (b + 1) & 0x1f;                    /* free the buffer */
}

static void cmd_eth(void) {
    print_("eth beats="); hex_(eth_beats, 8); putc_('\n');
}

void main(void)
{
    reg_uart_clkdiv = UART_DIV;
    print_("\n=== PicoSoC engine console ===\n");
    cmd_version();
    eth_init();
    menu();
    print_("> ");
    for (;;) {
        eth_handle();                 /* service one eth RX frame (weight upload) */
        int32_t c = reg_uart_data;
        if (c == -1) continue;
        char ch = (char)c;
        if (ch == '\r' || ch == '\n') { print_("> "); continue; }
        putc_(ch); putc_('\n');
        switch (ch) {
            case 'v': cmd_version(); break;
            case 'c': cmd_crc();     break;
            case 's': cmd_status();  break;
            case 'w': cmd_ddrwrite();break;
            case 'k': cmd_scan();    break;
            case 'e': cmd_eth();     break;
            case 'r': cmd_restart(); break;
            case '?':
            case 'h': menu();        break;
            default:  print_("? press ? for menu\n");
        }
        print_("> ");
    }
}
