// progmem_bram.v — PicoSoC program ROM forced into a real block RAM by DIRECTLY
// instantiating the RAMB16_S36_S36 primitive.  Inference collapsed the read-only,
// mostly-zero ROM to one RAMB18 + LUTROM, which updatemem cannot patch (it only
// rewrites BRAM).  A direct primitive instance is a clean, identifiable BRAM tile:
//   - firmware is baked into the INIT_xx params by bin2init.py (the PROGMEM_INIT
//     include) so the raw bitstream boots, AND
//   - the same tile can be re-patched in a built .bit with updatemem + a .mmi
//     generated from the RAM list (lowRISC bootrom pattern; data2mem -> updatemem).
//
// Same module name + interface as before, so picosoc_noflash is unchanged.
// Sim (no Xilinx unisim primitives) falls back to an inferred array + $readmemh.

module progmem (
    input  wire        clk,
    input  wire        rstn,
    input  wire        valid,
    output wire        ready,
    input  wire [31:0] addr,
    output wire [31:0] rdata
);
    localparam MEM_ADDR_MASK = 32'h0010_0000; // progmem region select bit

    reg ready_r;
    always @(posedge clk or negedge rstn)
        if (!rstn) ready_r <= 1'b0;
        else       ready_r <= valid && ((addr & MEM_ADDR_MASK) != 0);
    assign ready = ready_r;

`ifdef PROGMEM_RAMB
    // ---- synth: directly instantiated 1024 x 36 block RAM (32 data bits used) --
    // RAMB36E1 is exactly the primitive RAMB16_S36_S36 wraps (Vivado retarget
    // src/retarget/RAMB16_S36_S36.v), but full-depth: that wrapper caps the
    // address at 512 (ADDRARDADDR[14] tied 0) and only wires INIT_00..3F.  Here
    // we drive the full 10-bit word address at ADDRARDADDR[14:5] and bake
    // INIT_00..7F, so a single 36 Kb tile holds 1024 words.  Port A = sync read
    // (1-cycle latency, matching the inferred rdata_r); port B unused.  INIT baked
    // from firmware by bin2init.py into progmem_init.svh (generated by run.tcl
    // before synth, found via the src/soc include dir).  Literal filename —
    // Vivado synth rejects `include of a macro.
    wire [31:0] doa;
    RAMB36E1 #(
        .READ_WIDTH_A (36), .READ_WIDTH_B (36),
        .WRITE_WIDTH_A(36), .WRITE_WIDTH_B(36),
        .WRITE_MODE_A ("WRITE_FIRST"), .WRITE_MODE_B("WRITE_FIRST"),
        .SIM_DEVICE   ("7SERIES"),
        `include "progmem_init.svh"
    ) rom (
        .CLKARDCLK   (clk),    .ENARDEN  (1'b1),
        .ADDRARDADDR ({1'b0, addr[11:2], 5'b0}),    // [14:5] = 1024-word address
        .DIADI       (32'b0),  .DIPADIP  (4'b0),  .WEA   (4'b0),
        .DOADO       (doa),    .DOPADOP  (),
        .REGCEAREGCE (1'b0),   .RSTRAMARSTRAM(1'b0), .RSTREGARSTREG(1'b0),
        .CLKBWRCLK   (clk),    .ENBWREN  (1'b0),
        .ADDRBWRADDR (16'b0),  .DIBDI    (32'b0), .DIPBDIP(4'b0), .WEBWE(8'b0),
        .DOBDO       (),       .DOPBDOP  (),
        .REGCEB      (1'b0),   .RSTRAMB  (1'b0),  .RSTREGB(1'b0),
        .CASCADEINA  (1'b0),   .CASCADEINB(1'b0), .CASCADEOUTA(), .CASCADEOUTB(),
        .INJECTDBITERR(1'b0),  .INJECTSBITERR(1'b0),
        .DBITERR     (),       .SBITERR  (),      .ECCPARITY(), .RDADDRECC()
    );
    assign rdata = doa;
`else
    // ---- sim: inferred array initialised from PROGMEM_HEX ----
    reg [31:0] mem [0:1023];
`ifdef PROGMEM_HEX
    initial $readmemh(`PROGMEM_HEX, mem);
`endif
    reg [31:0] rdata_r;
    always @(posedge clk)
        rdata_r <= mem[addr[11:2]];
    assign rdata = rdata_r;
`endif
endmodule
